package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.ArticleKeyword;
import com.unbank.spider.mybatis.vo.ArticleKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int countByExample(ArticleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int deleteByExample(ArticleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int deleteByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int insert(ArticleKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int insertSelective(ArticleKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    List<ArticleKeyword> selectByExample(ArticleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    ArticleKeyword selectByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") ArticleKeyword record, @Param("example") ArticleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int updateByExample(@Param("record") ArticleKeyword record, @Param("example") ArticleKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int updateByPrimaryKeySelective(ArticleKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_keyword
     *
     * @mbggenerated Mon Dec 29 15:48:21 CST 2014
     */
    int updateByPrimaryKey(ArticleKeyword record);
}