package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.BhiInfo;
import com.unbank.spider.mybatis.vo.BhiInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BhiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int countByExample(BhiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int deleteByExample(BhiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int insert(BhiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int insertSelective(BhiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    List<BhiInfo> selectByExample(BhiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    BhiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") BhiInfo record, @Param("example") BhiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int updateByExample(@Param("record") BhiInfo record, @Param("example") BhiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int updateByPrimaryKeySelective(BhiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grab_bhi
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    int updateByPrimaryKey(BhiInfo record);
}