package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.ChinaventureFinancing;
import com.unbank.spider.mybatis.vo.ChinaventureFinancingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChinaventureFinancingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int countByExample(ChinaventureFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int deleteByExample(ChinaventureFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int insert(ChinaventureFinancing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int insertSelective(ChinaventureFinancing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    List<ChinaventureFinancing> selectByExample(ChinaventureFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    ChinaventureFinancing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ChinaventureFinancing record, @Param("example") ChinaventureFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int updateByExample(@Param("record") ChinaventureFinancing record, @Param("example") ChinaventureFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int updateByPrimaryKeySelective(ChinaventureFinancing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_financing
     *
     * @mbggenerated Fri Jan 09 14:31:01 CST 2015
     */
    int updateByPrimaryKey(ChinaventureFinancing record);
}