package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.HtBill;
import com.unbank.spider.mybatis.vo.HtBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HtBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int countByExample(HtBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int deleteByExample(HtBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int insert(HtBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int insertSelective(HtBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    List<HtBill> selectByExample(HtBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    HtBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") HtBill record, @Param("example") HtBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int updateByExample(@Param("record") HtBill record, @Param("example") HtBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int updateByPrimaryKeySelective(HtBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table htbill_bill
     *
     * @mbggenerated Thu Jan 22 10:50:24 CST 2015
     */
    int updateByPrimaryKey(HtBill record);
}