package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.JingyinmaoBill;
import com.unbank.spider.mybatis.vo.JingyinmaoBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JingyinmaoBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int countByExample(JingyinmaoBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int deleteByExample(JingyinmaoBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int insert(JingyinmaoBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int insertSelective(JingyinmaoBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    List<JingyinmaoBill> selectByExample(JingyinmaoBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    JingyinmaoBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int updateByExampleSelective(@Param("record") JingyinmaoBill record, @Param("example") JingyinmaoBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int updateByExample(@Param("record") JingyinmaoBill record, @Param("example") JingyinmaoBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int updateByPrimaryKeySelective(JingyinmaoBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingyinmao_bill
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    int updateByPrimaryKey(JingyinmaoBill record);
}