package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.PjtxBill;
import com.unbank.spider.mybatis.vo.PjtxBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PjtxBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int countByExample(PjtxBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int deleteByExample(PjtxBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int insert(PjtxBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int insertSelective(PjtxBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    List<PjtxBill> selectByExample(PjtxBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    PjtxBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int updateByExampleSelective(@Param("record") PjtxBill record, @Param("example") PjtxBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int updateByExample(@Param("record") PjtxBill record, @Param("example") PjtxBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int updateByPrimaryKeySelective(PjtxBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pjtx_bill
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    int updateByPrimaryKey(PjtxBill record);
}