package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.YangleeSilverLetter;
import com.unbank.spider.mybatis.vo.YangleeSilverLetterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YangleeSilverLetterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int countByExample(YangleeSilverLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int deleteByExample(YangleeSilverLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int insert(YangleeSilverLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int insertSelective(YangleeSilverLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    List<YangleeSilverLetter> selectByExample(YangleeSilverLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    YangleeSilverLetter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") YangleeSilverLetter record, @Param("example") YangleeSilverLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int updateByExample(@Param("record") YangleeSilverLetter record, @Param("example") YangleeSilverLetterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int updateByPrimaryKeySelective(YangleeSilverLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    int updateByPrimaryKey(YangleeSilverLetter record);
}