package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.ZgpjZhuantieBill;
import com.unbank.spider.mybatis.vo.ZgpjZhuantieBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZgpjZhuantieBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int countByExample(ZgpjZhuantieBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int deleteByExample(ZgpjZhuantieBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int insert(ZgpjZhuantieBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int insertSelective(ZgpjZhuantieBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    List<ZgpjZhuantieBill> selectByExample(ZgpjZhuantieBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    ZgpjZhuantieBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") ZgpjZhuantieBill record, @Param("example") ZgpjZhuantieBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int updateByExample(@Param("record") ZgpjZhuantieBill record, @Param("example") ZgpjZhuantieBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int updateByPrimaryKeySelective(ZgpjZhuantieBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_baojia1_bill
     *
     * @mbggenerated Wed Jan 21 14:59:19 CST 2015
     */
    int updateByPrimaryKey(ZgpjZhuantieBill record);
}