package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.ZgpjZhitieBill;
import com.unbank.spider.mybatis.vo.ZgpjZhitieBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZgpjZhitieBillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int countByExample(ZgpjZhitieBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int deleteByExample(ZgpjZhitieBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int insert(ZgpjZhitieBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int insertSelective(ZgpjZhitieBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	List<ZgpjZhitieBill> selectByExample(ZgpjZhitieBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	ZgpjZhitieBill selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ZgpjZhitieBill record,
			@Param("example") ZgpjZhitieBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int updateByExample(@Param("record") ZgpjZhitieBill record,
			@Param("example") ZgpjZhitieBillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int updateByPrimaryKeySelective(ZgpjZhitieBill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zgpj_baojia0_bill
	 * @mbggenerated  Wed Jan 21 14:58:15 CST 2015
	 */
	int updateByPrimaryKey(ZgpjZhitieBill record);
}