package com.unbank.spider.mybatis.client;

import com.unbank.spider.mybatis.vo.ZgpjPiaojuBill;
import com.unbank.spider.mybatis.vo.ZgpjPiaojuBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZgpjPiaojuBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int countByExample(ZgpjPiaojuBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int deleteByExample(ZgpjPiaojuBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int insert(ZgpjPiaojuBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int insertSelective(ZgpjPiaojuBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    List<ZgpjPiaojuBill> selectByExample(ZgpjPiaojuBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    ZgpjPiaojuBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") ZgpjPiaojuBill record, @Param("example") ZgpjPiaojuBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int updateByExample(@Param("record") ZgpjPiaojuBill record, @Param("example") ZgpjPiaojuBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int updateByPrimaryKeySelective(ZgpjPiaojuBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zgpj_piaoju_bill
     *
     * @mbggenerated Mon Jan 19 14:34:12 CST 2015
     */
    int updateByPrimaryKey(ZgpjPiaojuBill record);
}