package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class BhiInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.id
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_name
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_area
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_time
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private Date proTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_nature
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.firm_nature
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String firmNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_trade
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proTrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_assets
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proAssets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_stage
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_way
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_office
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_cycle
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_fund
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.equipment_source
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String equipmentSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.governing_unit
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String governingUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.address
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_facility
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proFacility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_content
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_department
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_people
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_tel
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.fax
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.postcode
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.detail_address
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grab_bhi.pro_intro
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    private String proIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.id
     *
     * @return the value of grab_bhi.id
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.id
     *
     * @param id the value for grab_bhi.id
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_name
     *
     * @return the value of grab_bhi.pro_name
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_name
     *
     * @param proName the value for grab_bhi.pro_name
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_area
     *
     * @return the value of grab_bhi.pro_area
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProArea() {
        return proArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_area
     *
     * @param proArea the value for grab_bhi.pro_area
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProArea(String proArea) {
        this.proArea = proArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_time
     *
     * @return the value of grab_bhi.pro_time
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public Date getProTime() {
        return proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_time
     *
     * @param proTime the value for grab_bhi.pro_time
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProTime(Date proTime) {
        this.proTime = proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_nature
     *
     * @return the value of grab_bhi.pro_nature
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProNature() {
        return proNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_nature
     *
     * @param proNature the value for grab_bhi.pro_nature
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProNature(String proNature) {
        this.proNature = proNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.firm_nature
     *
     * @return the value of grab_bhi.firm_nature
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getFirmNature() {
        return firmNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.firm_nature
     *
     * @param firmNature the value for grab_bhi.firm_nature
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setFirmNature(String firmNature) {
        this.firmNature = firmNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_trade
     *
     * @return the value of grab_bhi.pro_trade
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProTrade() {
        return proTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_trade
     *
     * @param proTrade the value for grab_bhi.pro_trade
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProTrade(String proTrade) {
        this.proTrade = proTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_assets
     *
     * @return the value of grab_bhi.pro_assets
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProAssets() {
        return proAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_assets
     *
     * @param proAssets the value for grab_bhi.pro_assets
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProAssets(String proAssets) {
        this.proAssets = proAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_stage
     *
     * @return the value of grab_bhi.pro_stage
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProStage() {
        return proStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_stage
     *
     * @param proStage the value for grab_bhi.pro_stage
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProStage(String proStage) {
        this.proStage = proStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_way
     *
     * @return the value of grab_bhi.pro_way
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProWay() {
        return proWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_way
     *
     * @param proWay the value for grab_bhi.pro_way
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProWay(String proWay) {
        this.proWay = proWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_office
     *
     * @return the value of grab_bhi.pro_office
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProOffice() {
        return proOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_office
     *
     * @param proOffice the value for grab_bhi.pro_office
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProOffice(String proOffice) {
        this.proOffice = proOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_cycle
     *
     * @return the value of grab_bhi.pro_cycle
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProCycle() {
        return proCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_cycle
     *
     * @param proCycle the value for grab_bhi.pro_cycle
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProCycle(String proCycle) {
        this.proCycle = proCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_fund
     *
     * @return the value of grab_bhi.pro_fund
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProFund() {
        return proFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_fund
     *
     * @param proFund the value for grab_bhi.pro_fund
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProFund(String proFund) {
        this.proFund = proFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.equipment_source
     *
     * @return the value of grab_bhi.equipment_source
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getEquipmentSource() {
        return equipmentSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.equipment_source
     *
     * @param equipmentSource the value for grab_bhi.equipment_source
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setEquipmentSource(String equipmentSource) {
        this.equipmentSource = equipmentSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.governing_unit
     *
     * @return the value of grab_bhi.governing_unit
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getGoverningUnit() {
        return governingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.governing_unit
     *
     * @param governingUnit the value for grab_bhi.governing_unit
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setGoverningUnit(String governingUnit) {
        this.governingUnit = governingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.address
     *
     * @return the value of grab_bhi.address
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.address
     *
     * @param address the value for grab_bhi.address
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_facility
     *
     * @return the value of grab_bhi.pro_facility
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProFacility() {
        return proFacility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_facility
     *
     * @param proFacility the value for grab_bhi.pro_facility
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProFacility(String proFacility) {
        this.proFacility = proFacility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_content
     *
     * @return the value of grab_bhi.pro_content
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProContent() {
        return proContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_content
     *
     * @param proContent the value for grab_bhi.pro_content
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProContent(String proContent) {
        this.proContent = proContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_department
     *
     * @return the value of grab_bhi.pro_department
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProDepartment() {
        return proDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_department
     *
     * @param proDepartment the value for grab_bhi.pro_department
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProDepartment(String proDepartment) {
        this.proDepartment = proDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_people
     *
     * @return the value of grab_bhi.pro_people
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProPeople() {
        return proPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_people
     *
     * @param proPeople the value for grab_bhi.pro_people
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProPeople(String proPeople) {
        this.proPeople = proPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_tel
     *
     * @return the value of grab_bhi.pro_tel
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProTel() {
        return proTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_tel
     *
     * @param proTel the value for grab_bhi.pro_tel
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProTel(String proTel) {
        this.proTel = proTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.fax
     *
     * @return the value of grab_bhi.fax
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.fax
     *
     * @param fax the value for grab_bhi.fax
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.postcode
     *
     * @return the value of grab_bhi.postcode
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.postcode
     *
     * @param postcode the value for grab_bhi.postcode
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.detail_address
     *
     * @return the value of grab_bhi.detail_address
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.detail_address
     *
     * @param detailAddress the value for grab_bhi.detail_address
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grab_bhi.pro_intro
     *
     * @return the value of grab_bhi.pro_intro
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public String getProIntro() {
        return proIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grab_bhi.pro_intro
     *
     * @param proIntro the value for grab_bhi.pro_intro
     *
     * @mbggenerated Mon Jan 05 13:54:58 CST 2015
     */
    public void setProIntro(String proIntro) {
        this.proIntro = proIntro;
    }
}