package com.unbank.spider.mybatis.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChinabillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public ChinabillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProLimitIsNull() {
            addCriterion("pro_limit is null");
            return (Criteria) this;
        }

        public Criteria andProLimitIsNotNull() {
            addCriterion("pro_limit is not null");
            return (Criteria) this;
        }

        public Criteria andProLimitEqualTo(String value) {
            addCriterion("pro_limit =", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitNotEqualTo(String value) {
            addCriterion("pro_limit <>", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitGreaterThan(String value) {
            addCriterion("pro_limit >", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitGreaterThanOrEqualTo(String value) {
            addCriterion("pro_limit >=", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitLessThan(String value) {
            addCriterion("pro_limit <", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitLessThanOrEqualTo(String value) {
            addCriterion("pro_limit <=", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitLike(String value) {
            addCriterion("pro_limit like", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitNotLike(String value) {
            addCriterion("pro_limit not like", value, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitIn(List<String> values) {
            addCriterion("pro_limit in", values, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitNotIn(List<String> values) {
            addCriterion("pro_limit not in", values, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitBetween(String value1, String value2) {
            addCriterion("pro_limit between", value1, value2, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProLimitNotBetween(String value1, String value2) {
            addCriterion("pro_limit not between", value1, value2, "proLimit");
            return (Criteria) this;
        }

        public Criteria andProMoneyIsNull() {
            addCriterion("pro_money is null");
            return (Criteria) this;
        }

        public Criteria andProMoneyIsNotNull() {
            addCriterion("pro_money is not null");
            return (Criteria) this;
        }

        public Criteria andProMoneyEqualTo(String value) {
            addCriterion("pro_money =", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyNotEqualTo(String value) {
            addCriterion("pro_money <>", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyGreaterThan(String value) {
            addCriterion("pro_money >", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyGreaterThanOrEqualTo(String value) {
            addCriterion("pro_money >=", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyLessThan(String value) {
            addCriterion("pro_money <", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyLessThanOrEqualTo(String value) {
            addCriterion("pro_money <=", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyLike(String value) {
            addCriterion("pro_money like", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyNotLike(String value) {
            addCriterion("pro_money not like", value, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyIn(List<String> values) {
            addCriterion("pro_money in", values, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyNotIn(List<String> values) {
            addCriterion("pro_money not in", values, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyBetween(String value1, String value2) {
            addCriterion("pro_money between", value1, value2, "proMoney");
            return (Criteria) this;
        }

        public Criteria andProMoneyNotBetween(String value1, String value2) {
            addCriterion("pro_money not between", value1, value2, "proMoney");
            return (Criteria) this;
        }

        public Criteria andDetailurlIsNull() {
            addCriterion("detailurl is null");
            return (Criteria) this;
        }

        public Criteria andDetailurlIsNotNull() {
            addCriterion("detailurl is not null");
            return (Criteria) this;
        }

        public Criteria andDetailurlEqualTo(String value) {
            addCriterion("detailurl =", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotEqualTo(String value) {
            addCriterion("detailurl <>", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlGreaterThan(String value) {
            addCriterion("detailurl >", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlGreaterThanOrEqualTo(String value) {
            addCriterion("detailurl >=", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLessThan(String value) {
            addCriterion("detailurl <", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLessThanOrEqualTo(String value) {
            addCriterion("detailurl <=", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLike(String value) {
            addCriterion("detailurl like", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotLike(String value) {
            addCriterion("detailurl not like", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlIn(List<String> values) {
            addCriterion("detailurl in", values, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotIn(List<String> values) {
            addCriterion("detailurl not in", values, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlBetween(String value1, String value2) {
            addCriterion("detailurl between", value1, value2, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotBetween(String value1, String value2) {
            addCriterion("detailurl not between", value1, value2, "detailurl");
            return (Criteria) this;
        }

        public Criteria andProTypeIsNull() {
            addCriterion("pro_type is null");
            return (Criteria) this;
        }

        public Criteria andProTypeIsNotNull() {
            addCriterion("pro_type is not null");
            return (Criteria) this;
        }

        public Criteria andProTypeEqualTo(String value) {
            addCriterion("pro_type =", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotEqualTo(String value) {
            addCriterion("pro_type <>", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeGreaterThan(String value) {
            addCriterion("pro_type >", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pro_type >=", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeLessThan(String value) {
            addCriterion("pro_type <", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeLessThanOrEqualTo(String value) {
            addCriterion("pro_type <=", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeLike(String value) {
            addCriterion("pro_type like", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotLike(String value) {
            addCriterion("pro_type not like", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeIn(List<String> values) {
            addCriterion("pro_type in", values, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotIn(List<String> values) {
            addCriterion("pro_type not in", values, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeBetween(String value1, String value2) {
            addCriterion("pro_type between", value1, value2, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotBetween(String value1, String value2) {
            addCriterion("pro_type not between", value1, value2, "proType");
            return (Criteria) this;
        }

        public Criteria andDrawerDateIsNull() {
            addCriterion("drawer_date is null");
            return (Criteria) this;
        }

        public Criteria andDrawerDateIsNotNull() {
            addCriterion("drawer_date is not null");
            return (Criteria) this;
        }

        public Criteria andDrawerDateEqualTo(String value) {
            addCriterion("drawer_date =", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateNotEqualTo(String value) {
            addCriterion("drawer_date <>", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateGreaterThan(String value) {
            addCriterion("drawer_date >", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateGreaterThanOrEqualTo(String value) {
            addCriterion("drawer_date >=", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateLessThan(String value) {
            addCriterion("drawer_date <", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateLessThanOrEqualTo(String value) {
            addCriterion("drawer_date <=", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateLike(String value) {
            addCriterion("drawer_date like", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateNotLike(String value) {
            addCriterion("drawer_date not like", value, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateIn(List<String> values) {
            addCriterion("drawer_date in", values, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateNotIn(List<String> values) {
            addCriterion("drawer_date not in", values, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateBetween(String value1, String value2) {
            addCriterion("drawer_date between", value1, value2, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andDrawerDateNotBetween(String value1, String value2) {
            addCriterion("drawer_date not between", value1, value2, "drawerDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNull() {
            addCriterion("issue_date is null");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNotNull() {
            addCriterion("issue_date is not null");
            return (Criteria) this;
        }

        public Criteria andIssueDateEqualTo(String value) {
            addCriterion("issue_date =", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotEqualTo(String value) {
            addCriterion("issue_date <>", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThan(String value) {
            addCriterion("issue_date >", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThanOrEqualTo(String value) {
            addCriterion("issue_date >=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThan(String value) {
            addCriterion("issue_date <", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThanOrEqualTo(String value) {
            addCriterion("issue_date <=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLike(String value) {
            addCriterion("issue_date like", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotLike(String value) {
            addCriterion("issue_date not like", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateIn(List<String> values) {
            addCriterion("issue_date in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotIn(List<String> values) {
            addCriterion("issue_date not in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateBetween(String value1, String value2) {
            addCriterion("issue_date between", value1, value2, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotBetween(String value1, String value2) {
            addCriterion("issue_date not between", value1, value2, "issueDate");
            return (Criteria) this;
        }

        public Criteria andProRateIsNull() {
            addCriterion("pro_rate is null");
            return (Criteria) this;
        }

        public Criteria andProRateIsNotNull() {
            addCriterion("pro_rate is not null");
            return (Criteria) this;
        }

        public Criteria andProRateEqualTo(String value) {
            addCriterion("pro_rate =", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateNotEqualTo(String value) {
            addCriterion("pro_rate <>", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateGreaterThan(String value) {
            addCriterion("pro_rate >", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateGreaterThanOrEqualTo(String value) {
            addCriterion("pro_rate >=", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateLessThan(String value) {
            addCriterion("pro_rate <", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateLessThanOrEqualTo(String value) {
            addCriterion("pro_rate <=", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateLike(String value) {
            addCriterion("pro_rate like", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateNotLike(String value) {
            addCriterion("pro_rate not like", value, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateIn(List<String> values) {
            addCriterion("pro_rate in", values, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateNotIn(List<String> values) {
            addCriterion("pro_rate not in", values, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateBetween(String value1, String value2) {
            addCriterion("pro_rate between", value1, value2, "proRate");
            return (Criteria) this;
        }

        public Criteria andProRateNotBetween(String value1, String value2) {
            addCriterion("pro_rate not between", value1, value2, "proRate");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceIsNull() {
            addCriterion("issue_place is null");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceIsNotNull() {
            addCriterion("issue_place is not null");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceEqualTo(String value) {
            addCriterion("issue_place =", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotEqualTo(String value) {
            addCriterion("issue_place <>", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceGreaterThan(String value) {
            addCriterion("issue_place >", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("issue_place >=", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceLessThan(String value) {
            addCriterion("issue_place <", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceLessThanOrEqualTo(String value) {
            addCriterion("issue_place <=", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceLike(String value) {
            addCriterion("issue_place like", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotLike(String value) {
            addCriterion("issue_place not like", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceIn(List<String> values) {
            addCriterion("issue_place in", values, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotIn(List<String> values) {
            addCriterion("issue_place not in", values, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceBetween(String value1, String value2) {
            addCriterion("issue_place between", value1, value2, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotBetween(String value1, String value2) {
            addCriterion("issue_place not between", value1, value2, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andProBankIsNull() {
            addCriterion("pro_bank is null");
            return (Criteria) this;
        }

        public Criteria andProBankIsNotNull() {
            addCriterion("pro_bank is not null");
            return (Criteria) this;
        }

        public Criteria andProBankEqualTo(String value) {
            addCriterion("pro_bank =", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankNotEqualTo(String value) {
            addCriterion("pro_bank <>", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankGreaterThan(String value) {
            addCriterion("pro_bank >", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankGreaterThanOrEqualTo(String value) {
            addCriterion("pro_bank >=", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankLessThan(String value) {
            addCriterion("pro_bank <", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankLessThanOrEqualTo(String value) {
            addCriterion("pro_bank <=", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankLike(String value) {
            addCriterion("pro_bank like", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankNotLike(String value) {
            addCriterion("pro_bank not like", value, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankIn(List<String> values) {
            addCriterion("pro_bank in", values, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankNotIn(List<String> values) {
            addCriterion("pro_bank not in", values, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankBetween(String value1, String value2) {
            addCriterion("pro_bank between", value1, value2, "proBank");
            return (Criteria) this;
        }

        public Criteria andProBankNotBetween(String value1, String value2) {
            addCriterion("pro_bank not between", value1, value2, "proBank");
            return (Criteria) this;
        }

        public Criteria andTradeSiteIsNull() {
            addCriterion("trade_site is null");
            return (Criteria) this;
        }

        public Criteria andTradeSiteIsNotNull() {
            addCriterion("trade_site is not null");
            return (Criteria) this;
        }

        public Criteria andTradeSiteEqualTo(String value) {
            addCriterion("trade_site =", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteNotEqualTo(String value) {
            addCriterion("trade_site <>", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteGreaterThan(String value) {
            addCriterion("trade_site >", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteGreaterThanOrEqualTo(String value) {
            addCriterion("trade_site >=", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteLessThan(String value) {
            addCriterion("trade_site <", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteLessThanOrEqualTo(String value) {
            addCriterion("trade_site <=", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteLike(String value) {
            addCriterion("trade_site like", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteNotLike(String value) {
            addCriterion("trade_site not like", value, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteIn(List<String> values) {
            addCriterion("trade_site in", values, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteNotIn(List<String> values) {
            addCriterion("trade_site not in", values, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteBetween(String value1, String value2) {
            addCriterion("trade_site between", value1, value2, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andTradeSiteNotBetween(String value1, String value2) {
            addCriterion("trade_site not between", value1, value2, "tradeSite");
            return (Criteria) this;
        }

        public Criteria andProTypeNameIsNull() {
            addCriterion("pro_type_name is null");
            return (Criteria) this;
        }

        public Criteria andProTypeNameIsNotNull() {
            addCriterion("pro_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andProTypeNameEqualTo(String value) {
            addCriterion("pro_type_name =", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameNotEqualTo(String value) {
            addCriterion("pro_type_name <>", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameGreaterThan(String value) {
            addCriterion("pro_type_name >", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("pro_type_name >=", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameLessThan(String value) {
            addCriterion("pro_type_name <", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameLessThanOrEqualTo(String value) {
            addCriterion("pro_type_name <=", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameLike(String value) {
            addCriterion("pro_type_name like", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameNotLike(String value) {
            addCriterion("pro_type_name not like", value, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameIn(List<String> values) {
            addCriterion("pro_type_name in", values, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameNotIn(List<String> values) {
            addCriterion("pro_type_name not in", values, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameBetween(String value1, String value2) {
            addCriterion("pro_type_name between", value1, value2, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andProTypeNameNotBetween(String value1, String value2) {
            addCriterion("pro_type_name not between", value1, value2, "proTypeName");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("TIME is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("TIME =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("TIME <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("TIME >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("TIME <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("TIME <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("TIME in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("TIME not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("TIME between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("TIME not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chinabill_bill
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 14 14:00:25 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chinabill_bill
     *
     * @mbggenerated Wed Jan 14 14:00:25 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}