package com.unbank.spider.mybatis.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChinaventureMergereventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public ChinaventureMergereventExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProNameIsNull() {
            addCriterion("pro_name is null");
            return (Criteria) this;
        }

        public Criteria andProNameIsNotNull() {
            addCriterion("pro_name is not null");
            return (Criteria) this;
        }

        public Criteria andProNameEqualTo(String value) {
            addCriterion("pro_name =", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotEqualTo(String value) {
            addCriterion("pro_name <>", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThan(String value) {
            addCriterion("pro_name >", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThanOrEqualTo(String value) {
            addCriterion("pro_name >=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThan(String value) {
            addCriterion("pro_name <", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThanOrEqualTo(String value) {
            addCriterion("pro_name <=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLike(String value) {
            addCriterion("pro_name like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotLike(String value) {
            addCriterion("pro_name not like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameIn(List<String> values) {
            addCriterion("pro_name in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotIn(List<String> values) {
            addCriterion("pro_name not in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameBetween(String value1, String value2) {
            addCriterion("pro_name between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotBetween(String value1, String value2) {
            addCriterion("pro_name not between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyIsNull() {
            addCriterion("whether_related_party is null");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyIsNotNull() {
            addCriterion("whether_related_party is not null");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyEqualTo(String value) {
            addCriterion("whether_related_party =", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyNotEqualTo(String value) {
            addCriterion("whether_related_party <>", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyGreaterThan(String value) {
            addCriterion("whether_related_party >", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyGreaterThanOrEqualTo(String value) {
            addCriterion("whether_related_party >=", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyLessThan(String value) {
            addCriterion("whether_related_party <", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyLessThanOrEqualTo(String value) {
            addCriterion("whether_related_party <=", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyLike(String value) {
            addCriterion("whether_related_party like", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyNotLike(String value) {
            addCriterion("whether_related_party not like", value, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyIn(List<String> values) {
            addCriterion("whether_related_party in", values, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyNotIn(List<String> values) {
            addCriterion("whether_related_party not in", values, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyBetween(String value1, String value2) {
            addCriterion("whether_related_party between", value1, value2, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andWhetherRelatedPartyNotBetween(String value1, String value2) {
            addCriterion("whether_related_party not between", value1, value2, "whetherRelatedParty");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionIsNull() {
            addCriterion("business_transaction is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionIsNotNull() {
            addCriterion("business_transaction is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionEqualTo(String value) {
            addCriterion("business_transaction =", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionNotEqualTo(String value) {
            addCriterion("business_transaction <>", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionGreaterThan(String value) {
            addCriterion("business_transaction >", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionGreaterThanOrEqualTo(String value) {
            addCriterion("business_transaction >=", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionLessThan(String value) {
            addCriterion("business_transaction <", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionLessThanOrEqualTo(String value) {
            addCriterion("business_transaction <=", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionLike(String value) {
            addCriterion("business_transaction like", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionNotLike(String value) {
            addCriterion("business_transaction not like", value, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionIn(List<String> values) {
            addCriterion("business_transaction in", values, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionNotIn(List<String> values) {
            addCriterion("business_transaction not in", values, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionBetween(String value1, String value2) {
            addCriterion("business_transaction between", value1, value2, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andBusinessTransactionNotBetween(String value1, String value2) {
            addCriterion("business_transaction not between", value1, value2, "businessTransaction");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderIsNull() {
            addCriterion("whether_cross_border is null");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderIsNotNull() {
            addCriterion("whether_cross_border is not null");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderEqualTo(String value) {
            addCriterion("whether_cross_border =", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderNotEqualTo(String value) {
            addCriterion("whether_cross_border <>", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderGreaterThan(String value) {
            addCriterion("whether_cross_border >", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderGreaterThanOrEqualTo(String value) {
            addCriterion("whether_cross_border >=", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderLessThan(String value) {
            addCriterion("whether_cross_border <", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderLessThanOrEqualTo(String value) {
            addCriterion("whether_cross_border <=", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderLike(String value) {
            addCriterion("whether_cross_border like", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderNotLike(String value) {
            addCriterion("whether_cross_border not like", value, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderIn(List<String> values) {
            addCriterion("whether_cross_border in", values, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderNotIn(List<String> values) {
            addCriterion("whether_cross_border not in", values, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderBetween(String value1, String value2) {
            addCriterion("whether_cross_border between", value1, value2, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andWhetherCrossBorderNotBetween(String value1, String value2) {
            addCriterion("whether_cross_border not between", value1, value2, "whetherCrossBorder");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryIsNull() {
            addCriterion("industry_category is null");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryIsNotNull() {
            addCriterion("industry_category is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryEqualTo(String value) {
            addCriterion("industry_category =", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryNotEqualTo(String value) {
            addCriterion("industry_category <>", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryGreaterThan(String value) {
            addCriterion("industry_category >", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("industry_category >=", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryLessThan(String value) {
            addCriterion("industry_category <", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryLessThanOrEqualTo(String value) {
            addCriterion("industry_category <=", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryLike(String value) {
            addCriterion("industry_category like", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryNotLike(String value) {
            addCriterion("industry_category not like", value, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryIn(List<String> values) {
            addCriterion("industry_category in", values, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryNotIn(List<String> values) {
            addCriterion("industry_category not in", values, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryBetween(String value1, String value2) {
            addCriterion("industry_category between", value1, value2, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andIndustryCategoryNotBetween(String value1, String value2) {
            addCriterion("industry_category not between", value1, value2, "industryCategory");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNull() {
            addCriterion("transaction_type is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNotNull() {
            addCriterion("transaction_type is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeEqualTo(String value) {
            addCriterion("transaction_type =", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotEqualTo(String value) {
            addCriterion("transaction_type <>", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThan(String value) {
            addCriterion("transaction_type >", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_type >=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThan(String value) {
            addCriterion("transaction_type <", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThanOrEqualTo(String value) {
            addCriterion("transaction_type <=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLike(String value) {
            addCriterion("transaction_type like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotLike(String value) {
            addCriterion("transaction_type not like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIn(List<String> values) {
            addCriterion("transaction_type in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotIn(List<String> values) {
            addCriterion("transaction_type not in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeBetween(String value1, String value2) {
            addCriterion("transaction_type between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotBetween(String value1, String value2) {
            addCriterion("transaction_type not between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTradingMannerIsNull() {
            addCriterion("trading_manner is null");
            return (Criteria) this;
        }

        public Criteria andTradingMannerIsNotNull() {
            addCriterion("trading_manner is not null");
            return (Criteria) this;
        }

        public Criteria andTradingMannerEqualTo(String value) {
            addCriterion("trading_manner =", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerNotEqualTo(String value) {
            addCriterion("trading_manner <>", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerGreaterThan(String value) {
            addCriterion("trading_manner >", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerGreaterThanOrEqualTo(String value) {
            addCriterion("trading_manner >=", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerLessThan(String value) {
            addCriterion("trading_manner <", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerLessThanOrEqualTo(String value) {
            addCriterion("trading_manner <=", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerLike(String value) {
            addCriterion("trading_manner like", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerNotLike(String value) {
            addCriterion("trading_manner not like", value, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerIn(List<String> values) {
            addCriterion("trading_manner in", values, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerNotIn(List<String> values) {
            addCriterion("trading_manner not in", values, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerBetween(String value1, String value2) {
            addCriterion("trading_manner between", value1, value2, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andTradingMannerNotBetween(String value1, String value2) {
            addCriterion("trading_manner not between", value1, value2, "tradingManner");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyIsNull() {
            addCriterion("buyer_company is null");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyIsNotNull() {
            addCriterion("buyer_company is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyEqualTo(String value) {
            addCriterion("buyer_company =", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyNotEqualTo(String value) {
            addCriterion("buyer_company <>", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyGreaterThan(String value) {
            addCriterion("buyer_company >", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_company >=", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyLessThan(String value) {
            addCriterion("buyer_company <", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyLessThanOrEqualTo(String value) {
            addCriterion("buyer_company <=", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyLike(String value) {
            addCriterion("buyer_company like", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyNotLike(String value) {
            addCriterion("buyer_company not like", value, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyIn(List<String> values) {
            addCriterion("buyer_company in", values, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyNotIn(List<String> values) {
            addCriterion("buyer_company not in", values, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyBetween(String value1, String value2) {
            addCriterion("buyer_company between", value1, value2, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andBuyerCompanyNotBetween(String value1, String value2) {
            addCriterion("buyer_company not between", value1, value2, "buyerCompany");
            return (Criteria) this;
        }

        public Criteria andLawFirmIsNull() {
            addCriterion("law_firm is null");
            return (Criteria) this;
        }

        public Criteria andLawFirmIsNotNull() {
            addCriterion("law_firm is not null");
            return (Criteria) this;
        }

        public Criteria andLawFirmEqualTo(String value) {
            addCriterion("law_firm =", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmNotEqualTo(String value) {
            addCriterion("law_firm <>", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmGreaterThan(String value) {
            addCriterion("law_firm >", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmGreaterThanOrEqualTo(String value) {
            addCriterion("law_firm >=", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmLessThan(String value) {
            addCriterion("law_firm <", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmLessThanOrEqualTo(String value) {
            addCriterion("law_firm <=", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmLike(String value) {
            addCriterion("law_firm like", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmNotLike(String value) {
            addCriterion("law_firm not like", value, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmIn(List<String> values) {
            addCriterion("law_firm in", values, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmNotIn(List<String> values) {
            addCriterion("law_firm not in", values, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmBetween(String value1, String value2) {
            addCriterion("law_firm between", value1, value2, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andLawFirmNotBetween(String value1, String value2) {
            addCriterion("law_firm not between", value1, value2, "lawFirm");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeIsNull() {
            addCriterion("transactions_over_time is null");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeIsNotNull() {
            addCriterion("transactions_over_time is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeEqualTo(String value) {
            addCriterion("transactions_over_time =", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeNotEqualTo(String value) {
            addCriterion("transactions_over_time <>", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeGreaterThan(String value) {
            addCriterion("transactions_over_time >", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeGreaterThanOrEqualTo(String value) {
            addCriterion("transactions_over_time >=", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeLessThan(String value) {
            addCriterion("transactions_over_time <", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeLessThanOrEqualTo(String value) {
            addCriterion("transactions_over_time <=", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeLike(String value) {
            addCriterion("transactions_over_time like", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeNotLike(String value) {
            addCriterion("transactions_over_time not like", value, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeIn(List<String> values) {
            addCriterion("transactions_over_time in", values, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeNotIn(List<String> values) {
            addCriterion("transactions_over_time not in", values, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeBetween(String value1, String value2) {
            addCriterion("transactions_over_time between", value1, value2, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andTransactionsOverTimeNotBetween(String value1, String value2) {
            addCriterion("transactions_over_time not between", value1, value2, "transactionsOverTime");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyIsNull() {
            addCriterion("evaluation_company is null");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyIsNotNull() {
            addCriterion("evaluation_company is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyEqualTo(String value) {
            addCriterion("evaluation_company =", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyNotEqualTo(String value) {
            addCriterion("evaluation_company <>", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyGreaterThan(String value) {
            addCriterion("evaluation_company >", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("evaluation_company >=", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyLessThan(String value) {
            addCriterion("evaluation_company <", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyLessThanOrEqualTo(String value) {
            addCriterion("evaluation_company <=", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyLike(String value) {
            addCriterion("evaluation_company like", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyNotLike(String value) {
            addCriterion("evaluation_company not like", value, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyIn(List<String> values) {
            addCriterion("evaluation_company in", values, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyNotIn(List<String> values) {
            addCriterion("evaluation_company not in", values, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyBetween(String value1, String value2) {
            addCriterion("evaluation_company between", value1, value2, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andEvaluationCompanyNotBetween(String value1, String value2) {
            addCriterion("evaluation_company not between", value1, value2, "evaluationCompany");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentIsNull() {
            addCriterion("pattern_payment is null");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentIsNotNull() {
            addCriterion("pattern_payment is not null");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentEqualTo(String value) {
            addCriterion("pattern_payment =", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentNotEqualTo(String value) {
            addCriterion("pattern_payment <>", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentGreaterThan(String value) {
            addCriterion("pattern_payment >", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentGreaterThanOrEqualTo(String value) {
            addCriterion("pattern_payment >=", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentLessThan(String value) {
            addCriterion("pattern_payment <", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentLessThanOrEqualTo(String value) {
            addCriterion("pattern_payment <=", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentLike(String value) {
            addCriterion("pattern_payment like", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentNotLike(String value) {
            addCriterion("pattern_payment not like", value, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentIn(List<String> values) {
            addCriterion("pattern_payment in", values, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentNotIn(List<String> values) {
            addCriterion("pattern_payment not in", values, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentBetween(String value1, String value2) {
            addCriterion("pattern_payment between", value1, value2, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andPatternPaymentNotBetween(String value1, String value2) {
            addCriterion("pattern_payment not between", value1, value2, "patternPayment");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusIsNull() {
            addCriterion("transaction_status is null");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusIsNotNull() {
            addCriterion("transaction_status is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusEqualTo(String value) {
            addCriterion("transaction_status =", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusNotEqualTo(String value) {
            addCriterion("transaction_status <>", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusGreaterThan(String value) {
            addCriterion("transaction_status >", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_status >=", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusLessThan(String value) {
            addCriterion("transaction_status <", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusLessThanOrEqualTo(String value) {
            addCriterion("transaction_status <=", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusLike(String value) {
            addCriterion("transaction_status like", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusNotLike(String value) {
            addCriterion("transaction_status not like", value, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusIn(List<String> values) {
            addCriterion("transaction_status in", values, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusNotIn(List<String> values) {
            addCriterion("transaction_status not in", values, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusBetween(String value1, String value2) {
            addCriterion("transaction_status between", value1, value2, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andTransactionStatusNotBetween(String value1, String value2) {
            addCriterion("transaction_status not between", value1, value2, "transactionStatus");
            return (Criteria) this;
        }

        public Criteria andDetailurlIsNull() {
            addCriterion("detailurl is null");
            return (Criteria) this;
        }

        public Criteria andDetailurlIsNotNull() {
            addCriterion("detailurl is not null");
            return (Criteria) this;
        }

        public Criteria andDetailurlEqualTo(String value) {
            addCriterion("detailurl =", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotEqualTo(String value) {
            addCriterion("detailurl <>", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlGreaterThan(String value) {
            addCriterion("detailurl >", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlGreaterThanOrEqualTo(String value) {
            addCriterion("detailurl >=", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLessThan(String value) {
            addCriterion("detailurl <", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLessThanOrEqualTo(String value) {
            addCriterion("detailurl <=", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLike(String value) {
            addCriterion("detailurl like", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotLike(String value) {
            addCriterion("detailurl not like", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlIn(List<String> values) {
            addCriterion("detailurl in", values, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotIn(List<String> values) {
            addCriterion("detailurl not in", values, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlBetween(String value1, String value2) {
            addCriterion("detailurl between", value1, value2, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotBetween(String value1, String value2) {
            addCriterion("detailurl not between", value1, value2, "detailurl");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountIsNull() {
            addCriterion("transaction_amount is null");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountIsNotNull() {
            addCriterion("transaction_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountEqualTo(String value) {
            addCriterion("transaction_amount =", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountNotEqualTo(String value) {
            addCriterion("transaction_amount <>", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountGreaterThan(String value) {
            addCriterion("transaction_amount >", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_amount >=", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountLessThan(String value) {
            addCriterion("transaction_amount <", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountLessThanOrEqualTo(String value) {
            addCriterion("transaction_amount <=", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountLike(String value) {
            addCriterion("transaction_amount like", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountNotLike(String value) {
            addCriterion("transaction_amount not like", value, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountIn(List<String> values) {
            addCriterion("transaction_amount in", values, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountNotIn(List<String> values) {
            addCriterion("transaction_amount not in", values, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountBetween(String value1, String value2) {
            addCriterion("transaction_amount between", value1, value2, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andTransactionAmountNotBetween(String value1, String value2) {
            addCriterion("transaction_amount not between", value1, value2, "transactionAmount");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationIsNull() {
            addCriterion("business_valuation is null");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationIsNotNull() {
            addCriterion("business_valuation is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationEqualTo(String value) {
            addCriterion("business_valuation =", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationNotEqualTo(String value) {
            addCriterion("business_valuation <>", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationGreaterThan(String value) {
            addCriterion("business_valuation >", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationGreaterThanOrEqualTo(String value) {
            addCriterion("business_valuation >=", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationLessThan(String value) {
            addCriterion("business_valuation <", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationLessThanOrEqualTo(String value) {
            addCriterion("business_valuation <=", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationLike(String value) {
            addCriterion("business_valuation like", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationNotLike(String value) {
            addCriterion("business_valuation not like", value, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationIn(List<String> values) {
            addCriterion("business_valuation in", values, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationNotIn(List<String> values) {
            addCriterion("business_valuation not in", values, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationBetween(String value1, String value2) {
            addCriterion("business_valuation between", value1, value2, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andBusinessValuationNotBetween(String value1, String value2) {
            addCriterion("business_valuation not between", value1, value2, "businessValuation");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankIsNull() {
            addCriterion("investment_bank is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankIsNotNull() {
            addCriterion("investment_bank is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankEqualTo(String value) {
            addCriterion("investment_bank =", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankNotEqualTo(String value) {
            addCriterion("investment_bank <>", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankGreaterThan(String value) {
            addCriterion("investment_bank >", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankGreaterThanOrEqualTo(String value) {
            addCriterion("investment_bank >=", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankLessThan(String value) {
            addCriterion("investment_bank <", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankLessThanOrEqualTo(String value) {
            addCriterion("investment_bank <=", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankLike(String value) {
            addCriterion("investment_bank like", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankNotLike(String value) {
            addCriterion("investment_bank not like", value, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankIn(List<String> values) {
            addCriterion("investment_bank in", values, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankNotIn(List<String> values) {
            addCriterion("investment_bank not in", values, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankBetween(String value1, String value2) {
            addCriterion("investment_bank between", value1, value2, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andInvestmentBankNotBetween(String value1, String value2) {
            addCriterion("investment_bank not between", value1, value2, "investmentBank");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseIsNull() {
            addCriterion("target_enterprise is null");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseIsNotNull() {
            addCriterion("target_enterprise is not null");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseEqualTo(String value) {
            addCriterion("target_enterprise =", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseNotEqualTo(String value) {
            addCriterion("target_enterprise <>", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseGreaterThan(String value) {
            addCriterion("target_enterprise >", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseGreaterThanOrEqualTo(String value) {
            addCriterion("target_enterprise >=", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseLessThan(String value) {
            addCriterion("target_enterprise <", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseLessThanOrEqualTo(String value) {
            addCriterion("target_enterprise <=", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseLike(String value) {
            addCriterion("target_enterprise like", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseNotLike(String value) {
            addCriterion("target_enterprise not like", value, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseIn(List<String> values) {
            addCriterion("target_enterprise in", values, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseNotIn(List<String> values) {
            addCriterion("target_enterprise not in", values, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseBetween(String value1, String value2) {
            addCriterion("target_enterprise between", value1, value2, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTargetEnterpriseNotBetween(String value1, String value2) {
            addCriterion("target_enterprise not between", value1, value2, "targetEnterprise");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeIsNull() {
            addCriterion("trading_attitude is null");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeIsNotNull() {
            addCriterion("trading_attitude is not null");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeEqualTo(String value) {
            addCriterion("trading_attitude =", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeNotEqualTo(String value) {
            addCriterion("trading_attitude <>", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeGreaterThan(String value) {
            addCriterion("trading_attitude >", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeGreaterThanOrEqualTo(String value) {
            addCriterion("trading_attitude >=", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeLessThan(String value) {
            addCriterion("trading_attitude <", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeLessThanOrEqualTo(String value) {
            addCriterion("trading_attitude <=", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeLike(String value) {
            addCriterion("trading_attitude like", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeNotLike(String value) {
            addCriterion("trading_attitude not like", value, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeIn(List<String> values) {
            addCriterion("trading_attitude in", values, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeNotIn(List<String> values) {
            addCriterion("trading_attitude not in", values, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeBetween(String value1, String value2) {
            addCriterion("trading_attitude between", value1, value2, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andTradingAttitudeNotBetween(String value1, String value2) {
            addCriterion("trading_attitude not between", value1, value2, "tradingAttitude");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmIsNull() {
            addCriterion("accounting_firm is null");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmIsNotNull() {
            addCriterion("accounting_firm is not null");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmEqualTo(String value) {
            addCriterion("accounting_firm =", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmNotEqualTo(String value) {
            addCriterion("accounting_firm <>", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmGreaterThan(String value) {
            addCriterion("accounting_firm >", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmGreaterThanOrEqualTo(String value) {
            addCriterion("accounting_firm >=", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmLessThan(String value) {
            addCriterion("accounting_firm <", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmLessThanOrEqualTo(String value) {
            addCriterion("accounting_firm <=", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmLike(String value) {
            addCriterion("accounting_firm like", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmNotLike(String value) {
            addCriterion("accounting_firm not like", value, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmIn(List<String> values) {
            addCriterion("accounting_firm in", values, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmNotIn(List<String> values) {
            addCriterion("accounting_firm not in", values, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmBetween(String value1, String value2) {
            addCriterion("accounting_firm between", value1, value2, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andAccountingFirmNotBetween(String value1, String value2) {
            addCriterion("accounting_firm not between", value1, value2, "accountingFirm");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeIsNull() {
            addCriterion("deal_announced_time is null");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeIsNotNull() {
            addCriterion("deal_announced_time is not null");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeEqualTo(String value) {
            addCriterion("deal_announced_time =", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeNotEqualTo(String value) {
            addCriterion("deal_announced_time <>", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeGreaterThan(String value) {
            addCriterion("deal_announced_time >", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("deal_announced_time >=", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeLessThan(String value) {
            addCriterion("deal_announced_time <", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeLessThanOrEqualTo(String value) {
            addCriterion("deal_announced_time <=", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeLike(String value) {
            addCriterion("deal_announced_time like", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeNotLike(String value) {
            addCriterion("deal_announced_time not like", value, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeIn(List<String> values) {
            addCriterion("deal_announced_time in", values, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeNotIn(List<String> values) {
            addCriterion("deal_announced_time not in", values, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeBetween(String value1, String value2) {
            addCriterion("deal_announced_time between", value1, value2, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andDealAnnouncedTimeNotBetween(String value1, String value2) {
            addCriterion("deal_announced_time not between", value1, value2, "dealAnnouncedTime");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("TIME is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("TIME =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("TIME <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("TIME >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("TIME <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("TIME <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("TIME in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("TIME not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("TIME between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("TIME not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 08 15:23:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chinaventure_mergerevent
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}