package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class ChinaventureMergerevent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.id
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.pro_name
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.whether_related_party
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String whetherRelatedParty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.business_transaction
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String businessTransaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.whether_cross_border
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String whetherCrossBorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.industry_category
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String industryCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.transaction_type
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.trading_manner
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String tradingManner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.buyer_company
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String buyerCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.law_firm
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String lawFirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.transactions_over_time
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String transactionsOverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.evaluation_company
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String evaluationCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.pattern_payment
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String patternPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.transaction_status
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String transactionStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.detailurl
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String detailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.transaction_amount
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String transactionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.business_valuation
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String businessValuation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.investment_bank
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String investmentBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.target_enterprise
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String targetEnterprise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.trading_attitude
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String tradingAttitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.accounting_firm
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String accountingFirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.deal_announced_time
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private String dealAnnouncedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinaventure_mergerevent.TIME
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.id
     *
     * @return the value of chinaventure_mergerevent.id
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.id
     *
     * @param id the value for chinaventure_mergerevent.id
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.pro_name
     *
     * @return the value of chinaventure_mergerevent.pro_name
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.pro_name
     *
     * @param proName the value for chinaventure_mergerevent.pro_name
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.whether_related_party
     *
     * @return the value of chinaventure_mergerevent.whether_related_party
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getWhetherRelatedParty() {
        return whetherRelatedParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.whether_related_party
     *
     * @param whetherRelatedParty the value for chinaventure_mergerevent.whether_related_party
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setWhetherRelatedParty(String whetherRelatedParty) {
        this.whetherRelatedParty = whetherRelatedParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.business_transaction
     *
     * @return the value of chinaventure_mergerevent.business_transaction
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getBusinessTransaction() {
        return businessTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.business_transaction
     *
     * @param businessTransaction the value for chinaventure_mergerevent.business_transaction
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setBusinessTransaction(String businessTransaction) {
        this.businessTransaction = businessTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.whether_cross_border
     *
     * @return the value of chinaventure_mergerevent.whether_cross_border
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getWhetherCrossBorder() {
        return whetherCrossBorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.whether_cross_border
     *
     * @param whetherCrossBorder the value for chinaventure_mergerevent.whether_cross_border
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setWhetherCrossBorder(String whetherCrossBorder) {
        this.whetherCrossBorder = whetherCrossBorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.industry_category
     *
     * @return the value of chinaventure_mergerevent.industry_category
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getIndustryCategory() {
        return industryCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.industry_category
     *
     * @param industryCategory the value for chinaventure_mergerevent.industry_category
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setIndustryCategory(String industryCategory) {
        this.industryCategory = industryCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.transaction_type
     *
     * @return the value of chinaventure_mergerevent.transaction_type
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.transaction_type
     *
     * @param transactionType the value for chinaventure_mergerevent.transaction_type
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.trading_manner
     *
     * @return the value of chinaventure_mergerevent.trading_manner
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getTradingManner() {
        return tradingManner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.trading_manner
     *
     * @param tradingManner the value for chinaventure_mergerevent.trading_manner
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTradingManner(String tradingManner) {
        this.tradingManner = tradingManner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.buyer_company
     *
     * @return the value of chinaventure_mergerevent.buyer_company
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getBuyerCompany() {
        return buyerCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.buyer_company
     *
     * @param buyerCompany the value for chinaventure_mergerevent.buyer_company
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setBuyerCompany(String buyerCompany) {
        this.buyerCompany = buyerCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.law_firm
     *
     * @return the value of chinaventure_mergerevent.law_firm
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getLawFirm() {
        return lawFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.law_firm
     *
     * @param lawFirm the value for chinaventure_mergerevent.law_firm
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setLawFirm(String lawFirm) {
        this.lawFirm = lawFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.transactions_over_time
     *
     * @return the value of chinaventure_mergerevent.transactions_over_time
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getTransactionsOverTime() {
        return transactionsOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.transactions_over_time
     *
     * @param transactionsOverTime the value for chinaventure_mergerevent.transactions_over_time
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTransactionsOverTime(String transactionsOverTime) {
        this.transactionsOverTime = transactionsOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.evaluation_company
     *
     * @return the value of chinaventure_mergerevent.evaluation_company
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getEvaluationCompany() {
        return evaluationCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.evaluation_company
     *
     * @param evaluationCompany the value for chinaventure_mergerevent.evaluation_company
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setEvaluationCompany(String evaluationCompany) {
        this.evaluationCompany = evaluationCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.pattern_payment
     *
     * @return the value of chinaventure_mergerevent.pattern_payment
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getPatternPayment() {
        return patternPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.pattern_payment
     *
     * @param patternPayment the value for chinaventure_mergerevent.pattern_payment
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setPatternPayment(String patternPayment) {
        this.patternPayment = patternPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.transaction_status
     *
     * @return the value of chinaventure_mergerevent.transaction_status
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.transaction_status
     *
     * @param transactionStatus the value for chinaventure_mergerevent.transaction_status
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTransactionStatus(String transactionStatus) {
        this.transactionStatus = transactionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.detailurl
     *
     * @return the value of chinaventure_mergerevent.detailurl
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getDetailurl() {
        return detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.detailurl
     *
     * @param detailurl the value for chinaventure_mergerevent.detailurl
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setDetailurl(String detailurl) {
        this.detailurl = detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.transaction_amount
     *
     * @return the value of chinaventure_mergerevent.transaction_amount
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.transaction_amount
     *
     * @param transactionAmount the value for chinaventure_mergerevent.transaction_amount
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTransactionAmount(String transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.business_valuation
     *
     * @return the value of chinaventure_mergerevent.business_valuation
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getBusinessValuation() {
        return businessValuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.business_valuation
     *
     * @param businessValuation the value for chinaventure_mergerevent.business_valuation
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setBusinessValuation(String businessValuation) {
        this.businessValuation = businessValuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.investment_bank
     *
     * @return the value of chinaventure_mergerevent.investment_bank
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getInvestmentBank() {
        return investmentBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.investment_bank
     *
     * @param investmentBank the value for chinaventure_mergerevent.investment_bank
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setInvestmentBank(String investmentBank) {
        this.investmentBank = investmentBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.target_enterprise
     *
     * @return the value of chinaventure_mergerevent.target_enterprise
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getTargetEnterprise() {
        return targetEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.target_enterprise
     *
     * @param targetEnterprise the value for chinaventure_mergerevent.target_enterprise
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTargetEnterprise(String targetEnterprise) {
        this.targetEnterprise = targetEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.trading_attitude
     *
     * @return the value of chinaventure_mergerevent.trading_attitude
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getTradingAttitude() {
        return tradingAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.trading_attitude
     *
     * @param tradingAttitude the value for chinaventure_mergerevent.trading_attitude
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTradingAttitude(String tradingAttitude) {
        this.tradingAttitude = tradingAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.accounting_firm
     *
     * @return the value of chinaventure_mergerevent.accounting_firm
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getAccountingFirm() {
        return accountingFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.accounting_firm
     *
     * @param accountingFirm the value for chinaventure_mergerevent.accounting_firm
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setAccountingFirm(String accountingFirm) {
        this.accountingFirm = accountingFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.deal_announced_time
     *
     * @return the value of chinaventure_mergerevent.deal_announced_time
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public String getDealAnnouncedTime() {
        return dealAnnouncedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.deal_announced_time
     *
     * @param dealAnnouncedTime the value for chinaventure_mergerevent.deal_announced_time
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setDealAnnouncedTime(String dealAnnouncedTime) {
        this.dealAnnouncedTime = dealAnnouncedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinaventure_mergerevent.TIME
     *
     * @return the value of chinaventure_mergerevent.TIME
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinaventure_mergerevent.TIME
     *
     * @param time the value for chinaventure_mergerevent.TIME
     *
     * @mbggenerated Thu Jan 08 15:23:53 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}