package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class CourtInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.id
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.announcement_type
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String announcementType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.published_edition
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String publishedEdition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.detailurl
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String detailurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.posting_date
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String postingDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.parties
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String parties;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.notice_people
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String noticePeople;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.bulletin_time
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String bulletinTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.TIME
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.area
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column court_announcement.content
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.id
	 * @return  the value of court_announcement.id
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.id
	 * @param id  the value for court_announcement.id
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.announcement_type
	 * @return  the value of court_announcement.announcement_type
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getAnnouncementType() {
		return announcementType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.announcement_type
	 * @param announcementType  the value for court_announcement.announcement_type
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setAnnouncementType(String announcementType) {
		this.announcementType = announcementType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.published_edition
	 * @return  the value of court_announcement.published_edition
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getPublishedEdition() {
		return publishedEdition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.published_edition
	 * @param publishedEdition  the value for court_announcement.published_edition
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setPublishedEdition(String publishedEdition) {
		this.publishedEdition = publishedEdition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.detailurl
	 * @return  the value of court_announcement.detailurl
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getDetailurl() {
		return detailurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.detailurl
	 * @param detailurl  the value for court_announcement.detailurl
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setDetailurl(String detailurl) {
		this.detailurl = detailurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.posting_date
	 * @return  the value of court_announcement.posting_date
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getPostingDate() {
		return postingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.posting_date
	 * @param postingDate  the value for court_announcement.posting_date
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setPostingDate(String postingDate) {
		this.postingDate = postingDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.parties
	 * @return  the value of court_announcement.parties
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getParties() {
		return parties;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.parties
	 * @param parties  the value for court_announcement.parties
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setParties(String parties) {
		this.parties = parties;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.notice_people
	 * @return  the value of court_announcement.notice_people
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getNoticePeople() {
		return noticePeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.notice_people
	 * @param noticePeople  the value for court_announcement.notice_people
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setNoticePeople(String noticePeople) {
		this.noticePeople = noticePeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.bulletin_time
	 * @return  the value of court_announcement.bulletin_time
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getBulletinTime() {
		return bulletinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.bulletin_time
	 * @param bulletinTime  the value for court_announcement.bulletin_time
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setBulletinTime(String bulletinTime) {
		this.bulletinTime = bulletinTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.TIME
	 * @return  the value of court_announcement.TIME
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.TIME
	 * @param time  the value for court_announcement.TIME
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.area
	 * @return  the value of court_announcement.area
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.area
	 * @param area  the value for court_announcement.area
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column court_announcement.content
	 * @return  the value of court_announcement.content
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column court_announcement.content
	 * @param content  the value for court_announcement.content
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}
}