package com.unbank.spider.mybatis.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourtInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public CourtInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeIsNull() {
			addCriterion("announcement_type is null");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeIsNotNull() {
			addCriterion("announcement_type is not null");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeEqualTo(String value) {
			addCriterion("announcement_type =", value, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeNotEqualTo(String value) {
			addCriterion("announcement_type <>", value, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeGreaterThan(String value) {
			addCriterion("announcement_type >", value, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeGreaterThanOrEqualTo(String value) {
			addCriterion("announcement_type >=", value, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeLessThan(String value) {
			addCriterion("announcement_type <", value, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeLessThanOrEqualTo(String value) {
			addCriterion("announcement_type <=", value, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeLike(String value) {
			addCriterion("announcement_type like", value, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeNotLike(String value) {
			addCriterion("announcement_type not like", value,
					"announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeIn(List<String> values) {
			addCriterion("announcement_type in", values, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeNotIn(List<String> values) {
			addCriterion("announcement_type not in", values, "announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeBetween(String value1, String value2) {
			addCriterion("announcement_type between", value1, value2,
					"announcementType");
			return (Criteria) this;
		}

		public Criteria andAnnouncementTypeNotBetween(String value1,
				String value2) {
			addCriterion("announcement_type not between", value1, value2,
					"announcementType");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionIsNull() {
			addCriterion("published_edition is null");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionIsNotNull() {
			addCriterion("published_edition is not null");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionEqualTo(String value) {
			addCriterion("published_edition =", value, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionNotEqualTo(String value) {
			addCriterion("published_edition <>", value, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionGreaterThan(String value) {
			addCriterion("published_edition >", value, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionGreaterThanOrEqualTo(String value) {
			addCriterion("published_edition >=", value, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionLessThan(String value) {
			addCriterion("published_edition <", value, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionLessThanOrEqualTo(String value) {
			addCriterion("published_edition <=", value, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionLike(String value) {
			addCriterion("published_edition like", value, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionNotLike(String value) {
			addCriterion("published_edition not like", value,
					"publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionIn(List<String> values) {
			addCriterion("published_edition in", values, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionNotIn(List<String> values) {
			addCriterion("published_edition not in", values, "publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionBetween(String value1, String value2) {
			addCriterion("published_edition between", value1, value2,
					"publishedEdition");
			return (Criteria) this;
		}

		public Criteria andPublishedEditionNotBetween(String value1,
				String value2) {
			addCriterion("published_edition not between", value1, value2,
					"publishedEdition");
			return (Criteria) this;
		}

		public Criteria andDetailurlIsNull() {
			addCriterion("detailurl is null");
			return (Criteria) this;
		}

		public Criteria andDetailurlIsNotNull() {
			addCriterion("detailurl is not null");
			return (Criteria) this;
		}

		public Criteria andDetailurlEqualTo(String value) {
			addCriterion("detailurl =", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotEqualTo(String value) {
			addCriterion("detailurl <>", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlGreaterThan(String value) {
			addCriterion("detailurl >", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlGreaterThanOrEqualTo(String value) {
			addCriterion("detailurl >=", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlLessThan(String value) {
			addCriterion("detailurl <", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlLessThanOrEqualTo(String value) {
			addCriterion("detailurl <=", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlLike(String value) {
			addCriterion("detailurl like", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotLike(String value) {
			addCriterion("detailurl not like", value, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlIn(List<String> values) {
			addCriterion("detailurl in", values, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotIn(List<String> values) {
			addCriterion("detailurl not in", values, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlBetween(String value1, String value2) {
			addCriterion("detailurl between", value1, value2, "detailurl");
			return (Criteria) this;
		}

		public Criteria andDetailurlNotBetween(String value1, String value2) {
			addCriterion("detailurl not between", value1, value2, "detailurl");
			return (Criteria) this;
		}

		public Criteria andPostingDateIsNull() {
			addCriterion("posting_date is null");
			return (Criteria) this;
		}

		public Criteria andPostingDateIsNotNull() {
			addCriterion("posting_date is not null");
			return (Criteria) this;
		}

		public Criteria andPostingDateEqualTo(String value) {
			addCriterion("posting_date =", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateNotEqualTo(String value) {
			addCriterion("posting_date <>", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateGreaterThan(String value) {
			addCriterion("posting_date >", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateGreaterThanOrEqualTo(String value) {
			addCriterion("posting_date >=", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateLessThan(String value) {
			addCriterion("posting_date <", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateLessThanOrEqualTo(String value) {
			addCriterion("posting_date <=", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateLike(String value) {
			addCriterion("posting_date like", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateNotLike(String value) {
			addCriterion("posting_date not like", value, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateIn(List<String> values) {
			addCriterion("posting_date in", values, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateNotIn(List<String> values) {
			addCriterion("posting_date not in", values, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateBetween(String value1, String value2) {
			addCriterion("posting_date between", value1, value2, "postingDate");
			return (Criteria) this;
		}

		public Criteria andPostingDateNotBetween(String value1, String value2) {
			addCriterion("posting_date not between", value1, value2,
					"postingDate");
			return (Criteria) this;
		}

		public Criteria andPartiesIsNull() {
			addCriterion("parties is null");
			return (Criteria) this;
		}

		public Criteria andPartiesIsNotNull() {
			addCriterion("parties is not null");
			return (Criteria) this;
		}

		public Criteria andPartiesEqualTo(String value) {
			addCriterion("parties =", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesNotEqualTo(String value) {
			addCriterion("parties <>", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesGreaterThan(String value) {
			addCriterion("parties >", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesGreaterThanOrEqualTo(String value) {
			addCriterion("parties >=", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesLessThan(String value) {
			addCriterion("parties <", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesLessThanOrEqualTo(String value) {
			addCriterion("parties <=", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesLike(String value) {
			addCriterion("parties like", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesNotLike(String value) {
			addCriterion("parties not like", value, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesIn(List<String> values) {
			addCriterion("parties in", values, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesNotIn(List<String> values) {
			addCriterion("parties not in", values, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesBetween(String value1, String value2) {
			addCriterion("parties between", value1, value2, "parties");
			return (Criteria) this;
		}

		public Criteria andPartiesNotBetween(String value1, String value2) {
			addCriterion("parties not between", value1, value2, "parties");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleIsNull() {
			addCriterion("notice_people is null");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleIsNotNull() {
			addCriterion("notice_people is not null");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleEqualTo(String value) {
			addCriterion("notice_people =", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleNotEqualTo(String value) {
			addCriterion("notice_people <>", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleGreaterThan(String value) {
			addCriterion("notice_people >", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleGreaterThanOrEqualTo(String value) {
			addCriterion("notice_people >=", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleLessThan(String value) {
			addCriterion("notice_people <", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleLessThanOrEqualTo(String value) {
			addCriterion("notice_people <=", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleLike(String value) {
			addCriterion("notice_people like", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleNotLike(String value) {
			addCriterion("notice_people not like", value, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleIn(List<String> values) {
			addCriterion("notice_people in", values, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleNotIn(List<String> values) {
			addCriterion("notice_people not in", values, "noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleBetween(String value1, String value2) {
			addCriterion("notice_people between", value1, value2,
					"noticePeople");
			return (Criteria) this;
		}

		public Criteria andNoticePeopleNotBetween(String value1, String value2) {
			addCriterion("notice_people not between", value1, value2,
					"noticePeople");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeIsNull() {
			addCriterion("bulletin_time is null");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeIsNotNull() {
			addCriterion("bulletin_time is not null");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeEqualTo(String value) {
			addCriterion("bulletin_time =", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeNotEqualTo(String value) {
			addCriterion("bulletin_time <>", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeGreaterThan(String value) {
			addCriterion("bulletin_time >", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeGreaterThanOrEqualTo(String value) {
			addCriterion("bulletin_time >=", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeLessThan(String value) {
			addCriterion("bulletin_time <", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeLessThanOrEqualTo(String value) {
			addCriterion("bulletin_time <=", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeLike(String value) {
			addCriterion("bulletin_time like", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeNotLike(String value) {
			addCriterion("bulletin_time not like", value, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeIn(List<String> values) {
			addCriterion("bulletin_time in", values, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeNotIn(List<String> values) {
			addCriterion("bulletin_time not in", values, "bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeBetween(String value1, String value2) {
			addCriterion("bulletin_time between", value1, value2,
					"bulletinTime");
			return (Criteria) this;
		}

		public Criteria andBulletinTimeNotBetween(String value1, String value2) {
			addCriterion("bulletin_time not between", value1, value2,
					"bulletinTime");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("TIME is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("TIME is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("TIME =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("TIME <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("TIME >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("TIME >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("TIME <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("TIME <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("TIME in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("TIME not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("TIME between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("TIME not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andAreaIsNull() {
			addCriterion("area is null");
			return (Criteria) this;
		}

		public Criteria andAreaIsNotNull() {
			addCriterion("area is not null");
			return (Criteria) this;
		}

		public Criteria andAreaEqualTo(String value) {
			addCriterion("area =", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotEqualTo(String value) {
			addCriterion("area <>", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThan(String value) {
			addCriterion("area >", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThanOrEqualTo(String value) {
			addCriterion("area >=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThan(String value) {
			addCriterion("area <", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThanOrEqualTo(String value) {
			addCriterion("area <=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLike(String value) {
			addCriterion("area like", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotLike(String value) {
			addCriterion("area not like", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaIn(List<String> values) {
			addCriterion("area in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotIn(List<String> values) {
			addCriterion("area not in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaBetween(String value1, String value2) {
			addCriterion("area between", value1, value2, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotBetween(String value1, String value2) {
			addCriterion("area not between", value1, value2, "area");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table court_announcement
	 * @mbggenerated  Mon Jan 05 17:44:53 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table court_announcement
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 31 16:02:17 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}