package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class Jdbill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.id
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.pro_name
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.bill_rate
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String billRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.pro_num
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String proNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.detailurl
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String detailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.publish_time
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.publish_date
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.bill_bank
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String billBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.bill_money
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String billMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.bill_day
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private String billDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jd_bill.TIME
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.id
     *
     * @return the value of jd_bill.id
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.id
     *
     * @param id the value for jd_bill.id
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.pro_name
     *
     * @return the value of jd_bill.pro_name
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.pro_name
     *
     * @param proName the value for jd_bill.pro_name
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.bill_rate
     *
     * @return the value of jd_bill.bill_rate
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getBillRate() {
        return billRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.bill_rate
     *
     * @param billRate the value for jd_bill.bill_rate
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setBillRate(String billRate) {
        this.billRate = billRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.pro_num
     *
     * @return the value of jd_bill.pro_num
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getProNum() {
        return proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.pro_num
     *
     * @param proNum the value for jd_bill.pro_num
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setProNum(String proNum) {
        this.proNum = proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.detailurl
     *
     * @return the value of jd_bill.detailurl
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getDetailurl() {
        return detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.detailurl
     *
     * @param detailurl the value for jd_bill.detailurl
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setDetailurl(String detailurl) {
        this.detailurl = detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.publish_time
     *
     * @return the value of jd_bill.publish_time
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.publish_time
     *
     * @param publishTime the value for jd_bill.publish_time
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setPublishTime(String publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.publish_date
     *
     * @return the value of jd_bill.publish_date
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.publish_date
     *
     * @param publishDate the value for jd_bill.publish_date
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.bill_bank
     *
     * @return the value of jd_bill.bill_bank
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getBillBank() {
        return billBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.bill_bank
     *
     * @param billBank the value for jd_bill.bill_bank
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setBillBank(String billBank) {
        this.billBank = billBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.bill_money
     *
     * @return the value of jd_bill.bill_money
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getBillMoney() {
        return billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.bill_money
     *
     * @param billMoney the value for jd_bill.bill_money
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setBillMoney(String billMoney) {
        this.billMoney = billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.bill_day
     *
     * @return the value of jd_bill.bill_day
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public String getBillDay() {
        return billDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.bill_day
     *
     * @param billDay the value for jd_bill.bill_day
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setBillDay(String billDay) {
        this.billDay = billDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jd_bill.TIME
     *
     * @return the value of jd_bill.TIME
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jd_bill.TIME
     *
     * @param time the value for jd_bill.TIME
     *
     * @mbggenerated Fri Dec 26 14:31:22 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }
}