package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class JingyinmaoBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.id
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_date
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.detailurl
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String detailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_name
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_money
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_limit
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_bank
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_num
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_time
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.pro_rate
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private String proRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingyinmao_bill.TIME
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.id
     *
     * @return the value of jingyinmao_bill.id
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.id
     *
     * @param id the value for jingyinmao_bill.id
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_date
     *
     * @return the value of jingyinmao_bill.pro_date
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProDate() {
        return proDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_date
     *
     * @param proDate the value for jingyinmao_bill.pro_date
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProDate(String proDate) {
        this.proDate = proDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.detailurl
     *
     * @return the value of jingyinmao_bill.detailurl
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getDetailurl() {
        return detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.detailurl
     *
     * @param detailurl the value for jingyinmao_bill.detailurl
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setDetailurl(String detailurl) {
        this.detailurl = detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_name
     *
     * @return the value of jingyinmao_bill.pro_name
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_name
     *
     * @param proName the value for jingyinmao_bill.pro_name
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_money
     *
     * @return the value of jingyinmao_bill.pro_money
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProMoney() {
        return proMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_money
     *
     * @param proMoney the value for jingyinmao_bill.pro_money
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProMoney(String proMoney) {
        this.proMoney = proMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_limit
     *
     * @return the value of jingyinmao_bill.pro_limit
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProLimit() {
        return proLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_limit
     *
     * @param proLimit the value for jingyinmao_bill.pro_limit
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProLimit(String proLimit) {
        this.proLimit = proLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_bank
     *
     * @return the value of jingyinmao_bill.pro_bank
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProBank() {
        return proBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_bank
     *
     * @param proBank the value for jingyinmao_bill.pro_bank
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProBank(String proBank) {
        this.proBank = proBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_num
     *
     * @return the value of jingyinmao_bill.pro_num
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProNum() {
        return proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_num
     *
     * @param proNum the value for jingyinmao_bill.pro_num
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProNum(String proNum) {
        this.proNum = proNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_time
     *
     * @return the value of jingyinmao_bill.pro_time
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProTime() {
        return proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_time
     *
     * @param proTime the value for jingyinmao_bill.pro_time
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProTime(String proTime) {
        this.proTime = proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.pro_rate
     *
     * @return the value of jingyinmao_bill.pro_rate
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public String getProRate() {
        return proRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.pro_rate
     *
     * @param proRate the value for jingyinmao_bill.pro_rate
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setProRate(String proRate) {
        this.proRate = proRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingyinmao_bill.TIME
     *
     * @return the value of jingyinmao_bill.TIME
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingyinmao_bill.TIME
     *
     * @param time the value for jingyinmao_bill.TIME
     *
     * @mbggenerated Tue Jan 06 10:18:23 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}