package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class PjtxBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.id
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.pro_money
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private String proMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.detailurl
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private String detailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.pro_place
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private String proPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.pro_rate
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private String proRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.look_type
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private String lookType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.pro_date
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private String proDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.bill_type
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pjtx_bill.TIME
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.id
     *
     * @return the value of pjtx_bill.id
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.id
     *
     * @param id the value for pjtx_bill.id
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.pro_money
     *
     * @return the value of pjtx_bill.pro_money
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public String getProMoney() {
        return proMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.pro_money
     *
     * @param proMoney the value for pjtx_bill.pro_money
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setProMoney(String proMoney) {
        this.proMoney = proMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.detailurl
     *
     * @return the value of pjtx_bill.detailurl
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public String getDetailurl() {
        return detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.detailurl
     *
     * @param detailurl the value for pjtx_bill.detailurl
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setDetailurl(String detailurl) {
        this.detailurl = detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.pro_place
     *
     * @return the value of pjtx_bill.pro_place
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public String getProPlace() {
        return proPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.pro_place
     *
     * @param proPlace the value for pjtx_bill.pro_place
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setProPlace(String proPlace) {
        this.proPlace = proPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.pro_rate
     *
     * @return the value of pjtx_bill.pro_rate
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public String getProRate() {
        return proRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.pro_rate
     *
     * @param proRate the value for pjtx_bill.pro_rate
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setProRate(String proRate) {
        this.proRate = proRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.look_type
     *
     * @return the value of pjtx_bill.look_type
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public String getLookType() {
        return lookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.look_type
     *
     * @param lookType the value for pjtx_bill.look_type
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setLookType(String lookType) {
        this.lookType = lookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.pro_date
     *
     * @return the value of pjtx_bill.pro_date
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public String getProDate() {
        return proDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.pro_date
     *
     * @param proDate the value for pjtx_bill.pro_date
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setProDate(String proDate) {
        this.proDate = proDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.bill_type
     *
     * @return the value of pjtx_bill.bill_type
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.bill_type
     *
     * @param billType the value for pjtx_bill.bill_type
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pjtx_bill.TIME
     *
     * @return the value of pjtx_bill.TIME
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pjtx_bill.TIME
     *
     * @param time the value for pjtx_bill.TIME
     *
     * @mbggenerated Wed Jan 21 14:21:06 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}