package com.unbank.spider.mybatis.vo;

import java.util.Date;

public class YangleeSilverLetter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.id
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.pro_name
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.pro_manage
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String proManage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.pro_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String proType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.distribution_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String distributionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.deal_structure
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String dealStructure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.issuing_scale
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String issuingScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.investment_manager
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String investmentManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.escrow_fee
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String escrowFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.established_time
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String establishedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.investment_way
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String investmentWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.investment_field
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String investmentField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.pub_house
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String pubHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.mature_time
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String matureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.product_feature
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String productFeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.pro_state
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String proState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.effective_rate
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String effectiveRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.anticipated_income
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String anticipatedIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.returns_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String returnsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.issue_date
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String issueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.lifetime_extension
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String lifetimeExtension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.financial_currency
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String financialCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.investment_manage_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String investmentManageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.redemptive_rate
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String redemptiveRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.detailurl
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String detailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.setup_scale
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String setupScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.escrow_line
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String escrowLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.credit_enhancement
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String creditEnhancement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.investment_threshold
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String investmentThreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.other_information
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String otherInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.issue_place
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String issuePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.release_object
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private String releaseObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yanglee_silverletter.TIME
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.id
     *
     * @return the value of yanglee_silverletter.id
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.id
     *
     * @param id the value for yanglee_silverletter.id
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.pro_name
     *
     * @return the value of yanglee_silverletter.pro_name
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.pro_name
     *
     * @param proName the value for yanglee_silverletter.pro_name
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setProName(String proName) {
        this.proName = proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.pro_manage
     *
     * @return the value of yanglee_silverletter.pro_manage
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getProManage() {
        return proManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.pro_manage
     *
     * @param proManage the value for yanglee_silverletter.pro_manage
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setProManage(String proManage) {
        this.proManage = proManage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.pro_type
     *
     * @return the value of yanglee_silverletter.pro_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getProType() {
        return proType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.pro_type
     *
     * @param proType the value for yanglee_silverletter.pro_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setProType(String proType) {
        this.proType = proType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.distribution_type
     *
     * @return the value of yanglee_silverletter.distribution_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getDistributionType() {
        return distributionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.distribution_type
     *
     * @param distributionType the value for yanglee_silverletter.distribution_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setDistributionType(String distributionType) {
        this.distributionType = distributionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.deal_structure
     *
     * @return the value of yanglee_silverletter.deal_structure
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getDealStructure() {
        return dealStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.deal_structure
     *
     * @param dealStructure the value for yanglee_silverletter.deal_structure
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setDealStructure(String dealStructure) {
        this.dealStructure = dealStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.issuing_scale
     *
     * @return the value of yanglee_silverletter.issuing_scale
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getIssuingScale() {
        return issuingScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.issuing_scale
     *
     * @param issuingScale the value for yanglee_silverletter.issuing_scale
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setIssuingScale(String issuingScale) {
        this.issuingScale = issuingScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.investment_manager
     *
     * @return the value of yanglee_silverletter.investment_manager
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getInvestmentManager() {
        return investmentManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.investment_manager
     *
     * @param investmentManager the value for yanglee_silverletter.investment_manager
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setInvestmentManager(String investmentManager) {
        this.investmentManager = investmentManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.escrow_fee
     *
     * @return the value of yanglee_silverletter.escrow_fee
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getEscrowFee() {
        return escrowFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.escrow_fee
     *
     * @param escrowFee the value for yanglee_silverletter.escrow_fee
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setEscrowFee(String escrowFee) {
        this.escrowFee = escrowFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.established_time
     *
     * @return the value of yanglee_silverletter.established_time
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getEstablishedTime() {
        return establishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.established_time
     *
     * @param establishedTime the value for yanglee_silverletter.established_time
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setEstablishedTime(String establishedTime) {
        this.establishedTime = establishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.investment_way
     *
     * @return the value of yanglee_silverletter.investment_way
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getInvestmentWay() {
        return investmentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.investment_way
     *
     * @param investmentWay the value for yanglee_silverletter.investment_way
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setInvestmentWay(String investmentWay) {
        this.investmentWay = investmentWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.investment_field
     *
     * @return the value of yanglee_silverletter.investment_field
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getInvestmentField() {
        return investmentField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.investment_field
     *
     * @param investmentField the value for yanglee_silverletter.investment_field
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setInvestmentField(String investmentField) {
        this.investmentField = investmentField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.pub_house
     *
     * @return the value of yanglee_silverletter.pub_house
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getPubHouse() {
        return pubHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.pub_house
     *
     * @param pubHouse the value for yanglee_silverletter.pub_house
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setPubHouse(String pubHouse) {
        this.pubHouse = pubHouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.mature_time
     *
     * @return the value of yanglee_silverletter.mature_time
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getMatureTime() {
        return matureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.mature_time
     *
     * @param matureTime the value for yanglee_silverletter.mature_time
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setMatureTime(String matureTime) {
        this.matureTime = matureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.product_feature
     *
     * @return the value of yanglee_silverletter.product_feature
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getProductFeature() {
        return productFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.product_feature
     *
     * @param productFeature the value for yanglee_silverletter.product_feature
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setProductFeature(String productFeature) {
        this.productFeature = productFeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.pro_state
     *
     * @return the value of yanglee_silverletter.pro_state
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getProState() {
        return proState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.pro_state
     *
     * @param proState the value for yanglee_silverletter.pro_state
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setProState(String proState) {
        this.proState = proState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.effective_rate
     *
     * @return the value of yanglee_silverletter.effective_rate
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getEffectiveRate() {
        return effectiveRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.effective_rate
     *
     * @param effectiveRate the value for yanglee_silverletter.effective_rate
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setEffectiveRate(String effectiveRate) {
        this.effectiveRate = effectiveRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.anticipated_income
     *
     * @return the value of yanglee_silverletter.anticipated_income
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getAnticipatedIncome() {
        return anticipatedIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.anticipated_income
     *
     * @param anticipatedIncome the value for yanglee_silverletter.anticipated_income
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setAnticipatedIncome(String anticipatedIncome) {
        this.anticipatedIncome = anticipatedIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.returns_type
     *
     * @return the value of yanglee_silverletter.returns_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getReturnsType() {
        return returnsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.returns_type
     *
     * @param returnsType the value for yanglee_silverletter.returns_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setReturnsType(String returnsType) {
        this.returnsType = returnsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.issue_date
     *
     * @return the value of yanglee_silverletter.issue_date
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.issue_date
     *
     * @param issueDate the value for yanglee_silverletter.issue_date
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setIssueDate(String issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.lifetime_extension
     *
     * @return the value of yanglee_silverletter.lifetime_extension
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getLifetimeExtension() {
        return lifetimeExtension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.lifetime_extension
     *
     * @param lifetimeExtension the value for yanglee_silverletter.lifetime_extension
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setLifetimeExtension(String lifetimeExtension) {
        this.lifetimeExtension = lifetimeExtension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.financial_currency
     *
     * @return the value of yanglee_silverletter.financial_currency
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getFinancialCurrency() {
        return financialCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.financial_currency
     *
     * @param financialCurrency the value for yanglee_silverletter.financial_currency
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setFinancialCurrency(String financialCurrency) {
        this.financialCurrency = financialCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.investment_manage_type
     *
     * @return the value of yanglee_silverletter.investment_manage_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getInvestmentManageType() {
        return investmentManageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.investment_manage_type
     *
     * @param investmentManageType the value for yanglee_silverletter.investment_manage_type
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setInvestmentManageType(String investmentManageType) {
        this.investmentManageType = investmentManageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.redemptive_rate
     *
     * @return the value of yanglee_silverletter.redemptive_rate
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getRedemptiveRate() {
        return redemptiveRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.redemptive_rate
     *
     * @param redemptiveRate the value for yanglee_silverletter.redemptive_rate
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setRedemptiveRate(String redemptiveRate) {
        this.redemptiveRate = redemptiveRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.detailurl
     *
     * @return the value of yanglee_silverletter.detailurl
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getDetailurl() {
        return detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.detailurl
     *
     * @param detailurl the value for yanglee_silverletter.detailurl
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setDetailurl(String detailurl) {
        this.detailurl = detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.setup_scale
     *
     * @return the value of yanglee_silverletter.setup_scale
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getSetupScale() {
        return setupScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.setup_scale
     *
     * @param setupScale the value for yanglee_silverletter.setup_scale
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setSetupScale(String setupScale) {
        this.setupScale = setupScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.escrow_line
     *
     * @return the value of yanglee_silverletter.escrow_line
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getEscrowLine() {
        return escrowLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.escrow_line
     *
     * @param escrowLine the value for yanglee_silverletter.escrow_line
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setEscrowLine(String escrowLine) {
        this.escrowLine = escrowLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.credit_enhancement
     *
     * @return the value of yanglee_silverletter.credit_enhancement
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getCreditEnhancement() {
        return creditEnhancement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.credit_enhancement
     *
     * @param creditEnhancement the value for yanglee_silverletter.credit_enhancement
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setCreditEnhancement(String creditEnhancement) {
        this.creditEnhancement = creditEnhancement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.investment_threshold
     *
     * @return the value of yanglee_silverletter.investment_threshold
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getInvestmentThreshold() {
        return investmentThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.investment_threshold
     *
     * @param investmentThreshold the value for yanglee_silverletter.investment_threshold
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setInvestmentThreshold(String investmentThreshold) {
        this.investmentThreshold = investmentThreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.other_information
     *
     * @return the value of yanglee_silverletter.other_information
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getOtherInformation() {
        return otherInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.other_information
     *
     * @param otherInformation the value for yanglee_silverletter.other_information
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setOtherInformation(String otherInformation) {
        this.otherInformation = otherInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.issue_place
     *
     * @return the value of yanglee_silverletter.issue_place
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getIssuePlace() {
        return issuePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.issue_place
     *
     * @param issuePlace the value for yanglee_silverletter.issue_place
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setIssuePlace(String issuePlace) {
        this.issuePlace = issuePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.release_object
     *
     * @return the value of yanglee_silverletter.release_object
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getReleaseObject() {
        return releaseObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.release_object
     *
     * @param releaseObject the value for yanglee_silverletter.release_object
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setReleaseObject(String releaseObject) {
        this.releaseObject = releaseObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yanglee_silverletter.TIME
     *
     * @return the value of yanglee_silverletter.TIME
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yanglee_silverletter.TIME
     *
     * @param time the value for yanglee_silverletter.TIME
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }
}