package com.unbank.spider.mybatis.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class YangleeSilverLetterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public YangleeSilverLetterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProNameIsNull() {
            addCriterion("pro_name is null");
            return (Criteria) this;
        }

        public Criteria andProNameIsNotNull() {
            addCriterion("pro_name is not null");
            return (Criteria) this;
        }

        public Criteria andProNameEqualTo(String value) {
            addCriterion("pro_name =", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotEqualTo(String value) {
            addCriterion("pro_name <>", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThan(String value) {
            addCriterion("pro_name >", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameGreaterThanOrEqualTo(String value) {
            addCriterion("pro_name >=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThan(String value) {
            addCriterion("pro_name <", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLessThanOrEqualTo(String value) {
            addCriterion("pro_name <=", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameLike(String value) {
            addCriterion("pro_name like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotLike(String value) {
            addCriterion("pro_name not like", value, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameIn(List<String> values) {
            addCriterion("pro_name in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotIn(List<String> values) {
            addCriterion("pro_name not in", values, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameBetween(String value1, String value2) {
            addCriterion("pro_name between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andProNameNotBetween(String value1, String value2) {
            addCriterion("pro_name not between", value1, value2, "proName");
            return (Criteria) this;
        }

        public Criteria andProManageIsNull() {
            addCriterion("pro_manage is null");
            return (Criteria) this;
        }

        public Criteria andProManageIsNotNull() {
            addCriterion("pro_manage is not null");
            return (Criteria) this;
        }

        public Criteria andProManageEqualTo(String value) {
            addCriterion("pro_manage =", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageNotEqualTo(String value) {
            addCriterion("pro_manage <>", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageGreaterThan(String value) {
            addCriterion("pro_manage >", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageGreaterThanOrEqualTo(String value) {
            addCriterion("pro_manage >=", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageLessThan(String value) {
            addCriterion("pro_manage <", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageLessThanOrEqualTo(String value) {
            addCriterion("pro_manage <=", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageLike(String value) {
            addCriterion("pro_manage like", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageNotLike(String value) {
            addCriterion("pro_manage not like", value, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageIn(List<String> values) {
            addCriterion("pro_manage in", values, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageNotIn(List<String> values) {
            addCriterion("pro_manage not in", values, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageBetween(String value1, String value2) {
            addCriterion("pro_manage between", value1, value2, "proManage");
            return (Criteria) this;
        }

        public Criteria andProManageNotBetween(String value1, String value2) {
            addCriterion("pro_manage not between", value1, value2, "proManage");
            return (Criteria) this;
        }

        public Criteria andProTypeIsNull() {
            addCriterion("pro_type is null");
            return (Criteria) this;
        }

        public Criteria andProTypeIsNotNull() {
            addCriterion("pro_type is not null");
            return (Criteria) this;
        }

        public Criteria andProTypeEqualTo(String value) {
            addCriterion("pro_type =", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotEqualTo(String value) {
            addCriterion("pro_type <>", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeGreaterThan(String value) {
            addCriterion("pro_type >", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pro_type >=", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeLessThan(String value) {
            addCriterion("pro_type <", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeLessThanOrEqualTo(String value) {
            addCriterion("pro_type <=", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeLike(String value) {
            addCriterion("pro_type like", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotLike(String value) {
            addCriterion("pro_type not like", value, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeIn(List<String> values) {
            addCriterion("pro_type in", values, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotIn(List<String> values) {
            addCriterion("pro_type not in", values, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeBetween(String value1, String value2) {
            addCriterion("pro_type between", value1, value2, "proType");
            return (Criteria) this;
        }

        public Criteria andProTypeNotBetween(String value1, String value2) {
            addCriterion("pro_type not between", value1, value2, "proType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeIsNull() {
            addCriterion("distribution_type is null");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeIsNotNull() {
            addCriterion("distribution_type is not null");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeEqualTo(String value) {
            addCriterion("distribution_type =", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeNotEqualTo(String value) {
            addCriterion("distribution_type <>", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeGreaterThan(String value) {
            addCriterion("distribution_type >", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("distribution_type >=", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeLessThan(String value) {
            addCriterion("distribution_type <", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeLessThanOrEqualTo(String value) {
            addCriterion("distribution_type <=", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeLike(String value) {
            addCriterion("distribution_type like", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeNotLike(String value) {
            addCriterion("distribution_type not like", value, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeIn(List<String> values) {
            addCriterion("distribution_type in", values, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeNotIn(List<String> values) {
            addCriterion("distribution_type not in", values, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeBetween(String value1, String value2) {
            addCriterion("distribution_type between", value1, value2, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDistributionTypeNotBetween(String value1, String value2) {
            addCriterion("distribution_type not between", value1, value2, "distributionType");
            return (Criteria) this;
        }

        public Criteria andDealStructureIsNull() {
            addCriterion("deal_structure is null");
            return (Criteria) this;
        }

        public Criteria andDealStructureIsNotNull() {
            addCriterion("deal_structure is not null");
            return (Criteria) this;
        }

        public Criteria andDealStructureEqualTo(String value) {
            addCriterion("deal_structure =", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureNotEqualTo(String value) {
            addCriterion("deal_structure <>", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureGreaterThan(String value) {
            addCriterion("deal_structure >", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureGreaterThanOrEqualTo(String value) {
            addCriterion("deal_structure >=", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureLessThan(String value) {
            addCriterion("deal_structure <", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureLessThanOrEqualTo(String value) {
            addCriterion("deal_structure <=", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureLike(String value) {
            addCriterion("deal_structure like", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureNotLike(String value) {
            addCriterion("deal_structure not like", value, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureIn(List<String> values) {
            addCriterion("deal_structure in", values, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureNotIn(List<String> values) {
            addCriterion("deal_structure not in", values, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureBetween(String value1, String value2) {
            addCriterion("deal_structure between", value1, value2, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andDealStructureNotBetween(String value1, String value2) {
            addCriterion("deal_structure not between", value1, value2, "dealStructure");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleIsNull() {
            addCriterion("issuing_scale is null");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleIsNotNull() {
            addCriterion("issuing_scale is not null");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleEqualTo(String value) {
            addCriterion("issuing_scale =", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleNotEqualTo(String value) {
            addCriterion("issuing_scale <>", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleGreaterThan(String value) {
            addCriterion("issuing_scale >", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleGreaterThanOrEqualTo(String value) {
            addCriterion("issuing_scale >=", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleLessThan(String value) {
            addCriterion("issuing_scale <", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleLessThanOrEqualTo(String value) {
            addCriterion("issuing_scale <=", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleLike(String value) {
            addCriterion("issuing_scale like", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleNotLike(String value) {
            addCriterion("issuing_scale not like", value, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleIn(List<String> values) {
            addCriterion("issuing_scale in", values, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleNotIn(List<String> values) {
            addCriterion("issuing_scale not in", values, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleBetween(String value1, String value2) {
            addCriterion("issuing_scale between", value1, value2, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andIssuingScaleNotBetween(String value1, String value2) {
            addCriterion("issuing_scale not between", value1, value2, "issuingScale");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerIsNull() {
            addCriterion("investment_manager is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerIsNotNull() {
            addCriterion("investment_manager is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerEqualTo(String value) {
            addCriterion("investment_manager =", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerNotEqualTo(String value) {
            addCriterion("investment_manager <>", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerGreaterThan(String value) {
            addCriterion("investment_manager >", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerGreaterThanOrEqualTo(String value) {
            addCriterion("investment_manager >=", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerLessThan(String value) {
            addCriterion("investment_manager <", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerLessThanOrEqualTo(String value) {
            addCriterion("investment_manager <=", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerLike(String value) {
            addCriterion("investment_manager like", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerNotLike(String value) {
            addCriterion("investment_manager not like", value, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerIn(List<String> values) {
            addCriterion("investment_manager in", values, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerNotIn(List<String> values) {
            addCriterion("investment_manager not in", values, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerBetween(String value1, String value2) {
            addCriterion("investment_manager between", value1, value2, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andInvestmentManagerNotBetween(String value1, String value2) {
            addCriterion("investment_manager not between", value1, value2, "investmentManager");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeIsNull() {
            addCriterion("escrow_fee is null");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeIsNotNull() {
            addCriterion("escrow_fee is not null");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeEqualTo(String value) {
            addCriterion("escrow_fee =", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeNotEqualTo(String value) {
            addCriterion("escrow_fee <>", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeGreaterThan(String value) {
            addCriterion("escrow_fee >", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeGreaterThanOrEqualTo(String value) {
            addCriterion("escrow_fee >=", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeLessThan(String value) {
            addCriterion("escrow_fee <", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeLessThanOrEqualTo(String value) {
            addCriterion("escrow_fee <=", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeLike(String value) {
            addCriterion("escrow_fee like", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeNotLike(String value) {
            addCriterion("escrow_fee not like", value, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeIn(List<String> values) {
            addCriterion("escrow_fee in", values, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeNotIn(List<String> values) {
            addCriterion("escrow_fee not in", values, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeBetween(String value1, String value2) {
            addCriterion("escrow_fee between", value1, value2, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEscrowFeeNotBetween(String value1, String value2) {
            addCriterion("escrow_fee not between", value1, value2, "escrowFee");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeIsNull() {
            addCriterion("established_time is null");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeIsNotNull() {
            addCriterion("established_time is not null");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeEqualTo(String value) {
            addCriterion("established_time =", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeNotEqualTo(String value) {
            addCriterion("established_time <>", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeGreaterThan(String value) {
            addCriterion("established_time >", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("established_time >=", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeLessThan(String value) {
            addCriterion("established_time <", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeLessThanOrEqualTo(String value) {
            addCriterion("established_time <=", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeLike(String value) {
            addCriterion("established_time like", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeNotLike(String value) {
            addCriterion("established_time not like", value, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeIn(List<String> values) {
            addCriterion("established_time in", values, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeNotIn(List<String> values) {
            addCriterion("established_time not in", values, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeBetween(String value1, String value2) {
            addCriterion("established_time between", value1, value2, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andEstablishedTimeNotBetween(String value1, String value2) {
            addCriterion("established_time not between", value1, value2, "establishedTime");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayIsNull() {
            addCriterion("investment_way is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayIsNotNull() {
            addCriterion("investment_way is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayEqualTo(String value) {
            addCriterion("investment_way =", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayNotEqualTo(String value) {
            addCriterion("investment_way <>", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayGreaterThan(String value) {
            addCriterion("investment_way >", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayGreaterThanOrEqualTo(String value) {
            addCriterion("investment_way >=", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayLessThan(String value) {
            addCriterion("investment_way <", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayLessThanOrEqualTo(String value) {
            addCriterion("investment_way <=", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayLike(String value) {
            addCriterion("investment_way like", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayNotLike(String value) {
            addCriterion("investment_way not like", value, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayIn(List<String> values) {
            addCriterion("investment_way in", values, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayNotIn(List<String> values) {
            addCriterion("investment_way not in", values, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayBetween(String value1, String value2) {
            addCriterion("investment_way between", value1, value2, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentWayNotBetween(String value1, String value2) {
            addCriterion("investment_way not between", value1, value2, "investmentWay");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldIsNull() {
            addCriterion("investment_field is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldIsNotNull() {
            addCriterion("investment_field is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldEqualTo(String value) {
            addCriterion("investment_field =", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldNotEqualTo(String value) {
            addCriterion("investment_field <>", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldGreaterThan(String value) {
            addCriterion("investment_field >", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldGreaterThanOrEqualTo(String value) {
            addCriterion("investment_field >=", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldLessThan(String value) {
            addCriterion("investment_field <", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldLessThanOrEqualTo(String value) {
            addCriterion("investment_field <=", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldLike(String value) {
            addCriterion("investment_field like", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldNotLike(String value) {
            addCriterion("investment_field not like", value, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldIn(List<String> values) {
            addCriterion("investment_field in", values, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldNotIn(List<String> values) {
            addCriterion("investment_field not in", values, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldBetween(String value1, String value2) {
            addCriterion("investment_field between", value1, value2, "investmentField");
            return (Criteria) this;
        }

        public Criteria andInvestmentFieldNotBetween(String value1, String value2) {
            addCriterion("investment_field not between", value1, value2, "investmentField");
            return (Criteria) this;
        }

        public Criteria andPubHouseIsNull() {
            addCriterion("pub_house is null");
            return (Criteria) this;
        }

        public Criteria andPubHouseIsNotNull() {
            addCriterion("pub_house is not null");
            return (Criteria) this;
        }

        public Criteria andPubHouseEqualTo(String value) {
            addCriterion("pub_house =", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseNotEqualTo(String value) {
            addCriterion("pub_house <>", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseGreaterThan(String value) {
            addCriterion("pub_house >", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseGreaterThanOrEqualTo(String value) {
            addCriterion("pub_house >=", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseLessThan(String value) {
            addCriterion("pub_house <", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseLessThanOrEqualTo(String value) {
            addCriterion("pub_house <=", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseLike(String value) {
            addCriterion("pub_house like", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseNotLike(String value) {
            addCriterion("pub_house not like", value, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseIn(List<String> values) {
            addCriterion("pub_house in", values, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseNotIn(List<String> values) {
            addCriterion("pub_house not in", values, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseBetween(String value1, String value2) {
            addCriterion("pub_house between", value1, value2, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andPubHouseNotBetween(String value1, String value2) {
            addCriterion("pub_house not between", value1, value2, "pubHouse");
            return (Criteria) this;
        }

        public Criteria andMatureTimeIsNull() {
            addCriterion("mature_time is null");
            return (Criteria) this;
        }

        public Criteria andMatureTimeIsNotNull() {
            addCriterion("mature_time is not null");
            return (Criteria) this;
        }

        public Criteria andMatureTimeEqualTo(String value) {
            addCriterion("mature_time =", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeNotEqualTo(String value) {
            addCriterion("mature_time <>", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeGreaterThan(String value) {
            addCriterion("mature_time >", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeGreaterThanOrEqualTo(String value) {
            addCriterion("mature_time >=", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeLessThan(String value) {
            addCriterion("mature_time <", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeLessThanOrEqualTo(String value) {
            addCriterion("mature_time <=", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeLike(String value) {
            addCriterion("mature_time like", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeNotLike(String value) {
            addCriterion("mature_time not like", value, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeIn(List<String> values) {
            addCriterion("mature_time in", values, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeNotIn(List<String> values) {
            addCriterion("mature_time not in", values, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeBetween(String value1, String value2) {
            addCriterion("mature_time between", value1, value2, "matureTime");
            return (Criteria) this;
        }

        public Criteria andMatureTimeNotBetween(String value1, String value2) {
            addCriterion("mature_time not between", value1, value2, "matureTime");
            return (Criteria) this;
        }

        public Criteria andProductFeatureIsNull() {
            addCriterion("product_feature is null");
            return (Criteria) this;
        }

        public Criteria andProductFeatureIsNotNull() {
            addCriterion("product_feature is not null");
            return (Criteria) this;
        }

        public Criteria andProductFeatureEqualTo(String value) {
            addCriterion("product_feature =", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureNotEqualTo(String value) {
            addCriterion("product_feature <>", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureGreaterThan(String value) {
            addCriterion("product_feature >", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureGreaterThanOrEqualTo(String value) {
            addCriterion("product_feature >=", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureLessThan(String value) {
            addCriterion("product_feature <", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureLessThanOrEqualTo(String value) {
            addCriterion("product_feature <=", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureLike(String value) {
            addCriterion("product_feature like", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureNotLike(String value) {
            addCriterion("product_feature not like", value, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureIn(List<String> values) {
            addCriterion("product_feature in", values, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureNotIn(List<String> values) {
            addCriterion("product_feature not in", values, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureBetween(String value1, String value2) {
            addCriterion("product_feature between", value1, value2, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProductFeatureNotBetween(String value1, String value2) {
            addCriterion("product_feature not between", value1, value2, "productFeature");
            return (Criteria) this;
        }

        public Criteria andProStateIsNull() {
            addCriterion("pro_state is null");
            return (Criteria) this;
        }

        public Criteria andProStateIsNotNull() {
            addCriterion("pro_state is not null");
            return (Criteria) this;
        }

        public Criteria andProStateEqualTo(String value) {
            addCriterion("pro_state =", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateNotEqualTo(String value) {
            addCriterion("pro_state <>", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateGreaterThan(String value) {
            addCriterion("pro_state >", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateGreaterThanOrEqualTo(String value) {
            addCriterion("pro_state >=", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateLessThan(String value) {
            addCriterion("pro_state <", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateLessThanOrEqualTo(String value) {
            addCriterion("pro_state <=", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateLike(String value) {
            addCriterion("pro_state like", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateNotLike(String value) {
            addCriterion("pro_state not like", value, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateIn(List<String> values) {
            addCriterion("pro_state in", values, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateNotIn(List<String> values) {
            addCriterion("pro_state not in", values, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateBetween(String value1, String value2) {
            addCriterion("pro_state between", value1, value2, "proState");
            return (Criteria) this;
        }

        public Criteria andProStateNotBetween(String value1, String value2) {
            addCriterion("pro_state not between", value1, value2, "proState");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateIsNull() {
            addCriterion("effective_rate is null");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateIsNotNull() {
            addCriterion("effective_rate is not null");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateEqualTo(String value) {
            addCriterion("effective_rate =", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateNotEqualTo(String value) {
            addCriterion("effective_rate <>", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateGreaterThan(String value) {
            addCriterion("effective_rate >", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateGreaterThanOrEqualTo(String value) {
            addCriterion("effective_rate >=", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateLessThan(String value) {
            addCriterion("effective_rate <", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateLessThanOrEqualTo(String value) {
            addCriterion("effective_rate <=", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateLike(String value) {
            addCriterion("effective_rate like", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateNotLike(String value) {
            addCriterion("effective_rate not like", value, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateIn(List<String> values) {
            addCriterion("effective_rate in", values, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateNotIn(List<String> values) {
            addCriterion("effective_rate not in", values, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateBetween(String value1, String value2) {
            addCriterion("effective_rate between", value1, value2, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andEffectiveRateNotBetween(String value1, String value2) {
            addCriterion("effective_rate not between", value1, value2, "effectiveRate");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeIsNull() {
            addCriterion("anticipated_income is null");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeIsNotNull() {
            addCriterion("anticipated_income is not null");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeEqualTo(String value) {
            addCriterion("anticipated_income =", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeNotEqualTo(String value) {
            addCriterion("anticipated_income <>", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeGreaterThan(String value) {
            addCriterion("anticipated_income >", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeGreaterThanOrEqualTo(String value) {
            addCriterion("anticipated_income >=", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeLessThan(String value) {
            addCriterion("anticipated_income <", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeLessThanOrEqualTo(String value) {
            addCriterion("anticipated_income <=", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeLike(String value) {
            addCriterion("anticipated_income like", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeNotLike(String value) {
            addCriterion("anticipated_income not like", value, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeIn(List<String> values) {
            addCriterion("anticipated_income in", values, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeNotIn(List<String> values) {
            addCriterion("anticipated_income not in", values, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeBetween(String value1, String value2) {
            addCriterion("anticipated_income between", value1, value2, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andAnticipatedIncomeNotBetween(String value1, String value2) {
            addCriterion("anticipated_income not between", value1, value2, "anticipatedIncome");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeIsNull() {
            addCriterion("returns_type is null");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeIsNotNull() {
            addCriterion("returns_type is not null");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeEqualTo(String value) {
            addCriterion("returns_type =", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeNotEqualTo(String value) {
            addCriterion("returns_type <>", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeGreaterThan(String value) {
            addCriterion("returns_type >", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("returns_type >=", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeLessThan(String value) {
            addCriterion("returns_type <", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeLessThanOrEqualTo(String value) {
            addCriterion("returns_type <=", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeLike(String value) {
            addCriterion("returns_type like", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeNotLike(String value) {
            addCriterion("returns_type not like", value, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeIn(List<String> values) {
            addCriterion("returns_type in", values, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeNotIn(List<String> values) {
            addCriterion("returns_type not in", values, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeBetween(String value1, String value2) {
            addCriterion("returns_type between", value1, value2, "returnsType");
            return (Criteria) this;
        }

        public Criteria andReturnsTypeNotBetween(String value1, String value2) {
            addCriterion("returns_type not between", value1, value2, "returnsType");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNull() {
            addCriterion("issue_date is null");
            return (Criteria) this;
        }

        public Criteria andIssueDateIsNotNull() {
            addCriterion("issue_date is not null");
            return (Criteria) this;
        }

        public Criteria andIssueDateEqualTo(String value) {
            addCriterion("issue_date =", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotEqualTo(String value) {
            addCriterion("issue_date <>", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThan(String value) {
            addCriterion("issue_date >", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateGreaterThanOrEqualTo(String value) {
            addCriterion("issue_date >=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThan(String value) {
            addCriterion("issue_date <", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLessThanOrEqualTo(String value) {
            addCriterion("issue_date <=", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateLike(String value) {
            addCriterion("issue_date like", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotLike(String value) {
            addCriterion("issue_date not like", value, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateIn(List<String> values) {
            addCriterion("issue_date in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotIn(List<String> values) {
            addCriterion("issue_date not in", values, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateBetween(String value1, String value2) {
            addCriterion("issue_date between", value1, value2, "issueDate");
            return (Criteria) this;
        }

        public Criteria andIssueDateNotBetween(String value1, String value2) {
            addCriterion("issue_date not between", value1, value2, "issueDate");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionIsNull() {
            addCriterion("lifetime_extension is null");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionIsNotNull() {
            addCriterion("lifetime_extension is not null");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionEqualTo(String value) {
            addCriterion("lifetime_extension =", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionNotEqualTo(String value) {
            addCriterion("lifetime_extension <>", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionGreaterThan(String value) {
            addCriterion("lifetime_extension >", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionGreaterThanOrEqualTo(String value) {
            addCriterion("lifetime_extension >=", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionLessThan(String value) {
            addCriterion("lifetime_extension <", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionLessThanOrEqualTo(String value) {
            addCriterion("lifetime_extension <=", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionLike(String value) {
            addCriterion("lifetime_extension like", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionNotLike(String value) {
            addCriterion("lifetime_extension not like", value, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionIn(List<String> values) {
            addCriterion("lifetime_extension in", values, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionNotIn(List<String> values) {
            addCriterion("lifetime_extension not in", values, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionBetween(String value1, String value2) {
            addCriterion("lifetime_extension between", value1, value2, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andLifetimeExtensionNotBetween(String value1, String value2) {
            addCriterion("lifetime_extension not between", value1, value2, "lifetimeExtension");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyIsNull() {
            addCriterion("financial_currency is null");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyIsNotNull() {
            addCriterion("financial_currency is not null");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyEqualTo(String value) {
            addCriterion("financial_currency =", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyNotEqualTo(String value) {
            addCriterion("financial_currency <>", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyGreaterThan(String value) {
            addCriterion("financial_currency >", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("financial_currency >=", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyLessThan(String value) {
            addCriterion("financial_currency <", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyLessThanOrEqualTo(String value) {
            addCriterion("financial_currency <=", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyLike(String value) {
            addCriterion("financial_currency like", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyNotLike(String value) {
            addCriterion("financial_currency not like", value, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyIn(List<String> values) {
            addCriterion("financial_currency in", values, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyNotIn(List<String> values) {
            addCriterion("financial_currency not in", values, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyBetween(String value1, String value2) {
            addCriterion("financial_currency between", value1, value2, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andFinancialCurrencyNotBetween(String value1, String value2) {
            addCriterion("financial_currency not between", value1, value2, "financialCurrency");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeIsNull() {
            addCriterion("investment_manage_type is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeIsNotNull() {
            addCriterion("investment_manage_type is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeEqualTo(String value) {
            addCriterion("investment_manage_type =", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeNotEqualTo(String value) {
            addCriterion("investment_manage_type <>", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeGreaterThan(String value) {
            addCriterion("investment_manage_type >", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeGreaterThanOrEqualTo(String value) {
            addCriterion("investment_manage_type >=", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeLessThan(String value) {
            addCriterion("investment_manage_type <", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeLessThanOrEqualTo(String value) {
            addCriterion("investment_manage_type <=", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeLike(String value) {
            addCriterion("investment_manage_type like", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeNotLike(String value) {
            addCriterion("investment_manage_type not like", value, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeIn(List<String> values) {
            addCriterion("investment_manage_type in", values, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeNotIn(List<String> values) {
            addCriterion("investment_manage_type not in", values, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeBetween(String value1, String value2) {
            addCriterion("investment_manage_type between", value1, value2, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andInvestmentManageTypeNotBetween(String value1, String value2) {
            addCriterion("investment_manage_type not between", value1, value2, "investmentManageType");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateIsNull() {
            addCriterion("redemptive_rate is null");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateIsNotNull() {
            addCriterion("redemptive_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateEqualTo(String value) {
            addCriterion("redemptive_rate =", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateNotEqualTo(String value) {
            addCriterion("redemptive_rate <>", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateGreaterThan(String value) {
            addCriterion("redemptive_rate >", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateGreaterThanOrEqualTo(String value) {
            addCriterion("redemptive_rate >=", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateLessThan(String value) {
            addCriterion("redemptive_rate <", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateLessThanOrEqualTo(String value) {
            addCriterion("redemptive_rate <=", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateLike(String value) {
            addCriterion("redemptive_rate like", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateNotLike(String value) {
            addCriterion("redemptive_rate not like", value, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateIn(List<String> values) {
            addCriterion("redemptive_rate in", values, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateNotIn(List<String> values) {
            addCriterion("redemptive_rate not in", values, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateBetween(String value1, String value2) {
            addCriterion("redemptive_rate between", value1, value2, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andRedemptiveRateNotBetween(String value1, String value2) {
            addCriterion("redemptive_rate not between", value1, value2, "redemptiveRate");
            return (Criteria) this;
        }

        public Criteria andDetailurlIsNull() {
            addCriterion("detailurl is null");
            return (Criteria) this;
        }

        public Criteria andDetailurlIsNotNull() {
            addCriterion("detailurl is not null");
            return (Criteria) this;
        }

        public Criteria andDetailurlEqualTo(String value) {
            addCriterion("detailurl =", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotEqualTo(String value) {
            addCriterion("detailurl <>", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlGreaterThan(String value) {
            addCriterion("detailurl >", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlGreaterThanOrEqualTo(String value) {
            addCriterion("detailurl >=", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLessThan(String value) {
            addCriterion("detailurl <", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLessThanOrEqualTo(String value) {
            addCriterion("detailurl <=", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlLike(String value) {
            addCriterion("detailurl like", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotLike(String value) {
            addCriterion("detailurl not like", value, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlIn(List<String> values) {
            addCriterion("detailurl in", values, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotIn(List<String> values) {
            addCriterion("detailurl not in", values, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlBetween(String value1, String value2) {
            addCriterion("detailurl between", value1, value2, "detailurl");
            return (Criteria) this;
        }

        public Criteria andDetailurlNotBetween(String value1, String value2) {
            addCriterion("detailurl not between", value1, value2, "detailurl");
            return (Criteria) this;
        }

        public Criteria andSetupScaleIsNull() {
            addCriterion("setup_scale is null");
            return (Criteria) this;
        }

        public Criteria andSetupScaleIsNotNull() {
            addCriterion("setup_scale is not null");
            return (Criteria) this;
        }

        public Criteria andSetupScaleEqualTo(String value) {
            addCriterion("setup_scale =", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleNotEqualTo(String value) {
            addCriterion("setup_scale <>", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleGreaterThan(String value) {
            addCriterion("setup_scale >", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleGreaterThanOrEqualTo(String value) {
            addCriterion("setup_scale >=", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleLessThan(String value) {
            addCriterion("setup_scale <", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleLessThanOrEqualTo(String value) {
            addCriterion("setup_scale <=", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleLike(String value) {
            addCriterion("setup_scale like", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleNotLike(String value) {
            addCriterion("setup_scale not like", value, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleIn(List<String> values) {
            addCriterion("setup_scale in", values, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleNotIn(List<String> values) {
            addCriterion("setup_scale not in", values, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleBetween(String value1, String value2) {
            addCriterion("setup_scale between", value1, value2, "setupScale");
            return (Criteria) this;
        }

        public Criteria andSetupScaleNotBetween(String value1, String value2) {
            addCriterion("setup_scale not between", value1, value2, "setupScale");
            return (Criteria) this;
        }

        public Criteria andEscrowLineIsNull() {
            addCriterion("escrow_line is null");
            return (Criteria) this;
        }

        public Criteria andEscrowLineIsNotNull() {
            addCriterion("escrow_line is not null");
            return (Criteria) this;
        }

        public Criteria andEscrowLineEqualTo(String value) {
            addCriterion("escrow_line =", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineNotEqualTo(String value) {
            addCriterion("escrow_line <>", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineGreaterThan(String value) {
            addCriterion("escrow_line >", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineGreaterThanOrEqualTo(String value) {
            addCriterion("escrow_line >=", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineLessThan(String value) {
            addCriterion("escrow_line <", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineLessThanOrEqualTo(String value) {
            addCriterion("escrow_line <=", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineLike(String value) {
            addCriterion("escrow_line like", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineNotLike(String value) {
            addCriterion("escrow_line not like", value, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineIn(List<String> values) {
            addCriterion("escrow_line in", values, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineNotIn(List<String> values) {
            addCriterion("escrow_line not in", values, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineBetween(String value1, String value2) {
            addCriterion("escrow_line between", value1, value2, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andEscrowLineNotBetween(String value1, String value2) {
            addCriterion("escrow_line not between", value1, value2, "escrowLine");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementIsNull() {
            addCriterion("credit_enhancement is null");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementIsNotNull() {
            addCriterion("credit_enhancement is not null");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementEqualTo(String value) {
            addCriterion("credit_enhancement =", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementNotEqualTo(String value) {
            addCriterion("credit_enhancement <>", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementGreaterThan(String value) {
            addCriterion("credit_enhancement >", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementGreaterThanOrEqualTo(String value) {
            addCriterion("credit_enhancement >=", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementLessThan(String value) {
            addCriterion("credit_enhancement <", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementLessThanOrEqualTo(String value) {
            addCriterion("credit_enhancement <=", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementLike(String value) {
            addCriterion("credit_enhancement like", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementNotLike(String value) {
            addCriterion("credit_enhancement not like", value, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementIn(List<String> values) {
            addCriterion("credit_enhancement in", values, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementNotIn(List<String> values) {
            addCriterion("credit_enhancement not in", values, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementBetween(String value1, String value2) {
            addCriterion("credit_enhancement between", value1, value2, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andCreditEnhancementNotBetween(String value1, String value2) {
            addCriterion("credit_enhancement not between", value1, value2, "creditEnhancement");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdIsNull() {
            addCriterion("investment_threshold is null");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdIsNotNull() {
            addCriterion("investment_threshold is not null");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdEqualTo(String value) {
            addCriterion("investment_threshold =", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdNotEqualTo(String value) {
            addCriterion("investment_threshold <>", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdGreaterThan(String value) {
            addCriterion("investment_threshold >", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdGreaterThanOrEqualTo(String value) {
            addCriterion("investment_threshold >=", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdLessThan(String value) {
            addCriterion("investment_threshold <", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdLessThanOrEqualTo(String value) {
            addCriterion("investment_threshold <=", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdLike(String value) {
            addCriterion("investment_threshold like", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdNotLike(String value) {
            addCriterion("investment_threshold not like", value, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdIn(List<String> values) {
            addCriterion("investment_threshold in", values, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdNotIn(List<String> values) {
            addCriterion("investment_threshold not in", values, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdBetween(String value1, String value2) {
            addCriterion("investment_threshold between", value1, value2, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andInvestmentThresholdNotBetween(String value1, String value2) {
            addCriterion("investment_threshold not between", value1, value2, "investmentThreshold");
            return (Criteria) this;
        }

        public Criteria andOtherInformationIsNull() {
            addCriterion("other_information is null");
            return (Criteria) this;
        }

        public Criteria andOtherInformationIsNotNull() {
            addCriterion("other_information is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInformationEqualTo(String value) {
            addCriterion("other_information =", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationNotEqualTo(String value) {
            addCriterion("other_information <>", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationGreaterThan(String value) {
            addCriterion("other_information >", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationGreaterThanOrEqualTo(String value) {
            addCriterion("other_information >=", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationLessThan(String value) {
            addCriterion("other_information <", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationLessThanOrEqualTo(String value) {
            addCriterion("other_information <=", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationLike(String value) {
            addCriterion("other_information like", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationNotLike(String value) {
            addCriterion("other_information not like", value, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationIn(List<String> values) {
            addCriterion("other_information in", values, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationNotIn(List<String> values) {
            addCriterion("other_information not in", values, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationBetween(String value1, String value2) {
            addCriterion("other_information between", value1, value2, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andOtherInformationNotBetween(String value1, String value2) {
            addCriterion("other_information not between", value1, value2, "otherInformation");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceIsNull() {
            addCriterion("issue_place is null");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceIsNotNull() {
            addCriterion("issue_place is not null");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceEqualTo(String value) {
            addCriterion("issue_place =", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotEqualTo(String value) {
            addCriterion("issue_place <>", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceGreaterThan(String value) {
            addCriterion("issue_place >", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("issue_place >=", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceLessThan(String value) {
            addCriterion("issue_place <", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceLessThanOrEqualTo(String value) {
            addCriterion("issue_place <=", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceLike(String value) {
            addCriterion("issue_place like", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotLike(String value) {
            addCriterion("issue_place not like", value, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceIn(List<String> values) {
            addCriterion("issue_place in", values, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotIn(List<String> values) {
            addCriterion("issue_place not in", values, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceBetween(String value1, String value2) {
            addCriterion("issue_place between", value1, value2, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andIssuePlaceNotBetween(String value1, String value2) {
            addCriterion("issue_place not between", value1, value2, "issuePlace");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectIsNull() {
            addCriterion("release_object is null");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectIsNotNull() {
            addCriterion("release_object is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectEqualTo(String value) {
            addCriterion("release_object =", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectNotEqualTo(String value) {
            addCriterion("release_object <>", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectGreaterThan(String value) {
            addCriterion("release_object >", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectGreaterThanOrEqualTo(String value) {
            addCriterion("release_object >=", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectLessThan(String value) {
            addCriterion("release_object <", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectLessThanOrEqualTo(String value) {
            addCriterion("release_object <=", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectLike(String value) {
            addCriterion("release_object like", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectNotLike(String value) {
            addCriterion("release_object not like", value, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectIn(List<String> values) {
            addCriterion("release_object in", values, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectNotIn(List<String> values) {
            addCriterion("release_object not in", values, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectBetween(String value1, String value2) {
            addCriterion("release_object between", value1, value2, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andReleaseObjectNotBetween(String value1, String value2) {
            addCriterion("release_object not between", value1, value2, "releaseObject");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("TIME is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("TIME =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("TIME <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("TIME >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("TIME <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("TIME <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("TIME in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("TIME not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("TIME between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("TIME not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 05 10:41:35 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yanglee_silverletter
     *
     * @mbggenerated Mon Jan 05 10:41:35 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}